// Generated by electe-web/scripts/export-tools-repo.ts from electe-migration@8e52bf6 on 2026-09-29. Do not edit here: change the source and re-export.
// Source: electe-web/src/lib/tools/data.ts
/**
 * Parsing and shaping for the three data tools — histogram, chart
 * builder, CSV merge.
 *
 * ALL OF IT PURE, and separate from the components for the reason
 * `overrideShape.ts` and `ogCard.ts` are separate from their server
 * halves: this is where the bugs live, and a function that needs a
 * browser to run is a function nobody tests. Delimiter sniffing,
 * quoted-field handling and header alignment are exactly the code that
 * looks obviously right and is obviously wrong on the third file
 * somebody tries.
 */

/* ─────────────────────────── numbers ─────────────────────────── */

/**
 * Numbers out of a pasted blob.
 *
 * Separators are comma, semicolon, whitespace or a new line — whatever a
 * spreadsheet paste happens to carry. The DECIMAL is a point, stated in
 * the field's help text rather than guessed at: with commas doing
 * separator duty, `1,5` is genuinely ambiguous between one-point-five and
 * two values, and a tool that silently picks one is a tool that silently
 * halves somebody's dataset.
 */
export function parseSeries(input: string): number[] {
  return input
    .split(/[\s,;]+/)
    .map((token) => Number.parseFloat(token))
    .filter((value) => Number.isFinite(value))
}

export interface Bin {
  count: number
  from: number
  to: number
}

/**
 * Equal-width bins over a series.
 *
 * The last bin is CLOSED at the top — `[from, to)` for every bin except
 * the final one, which is `[from, to]`. Without that the maximum value
 * falls outside every bin and vanishes from its own histogram, which is
 * the classic off-by-one here and is invisible unless you count.
 *
 * A constant series has no range to divide, so it gets one bin holding
 * everything rather than a division by zero.
 */
export function histogram(values: number[], binCount: number): Bin[] {
  const xs = values.filter((v) => Number.isFinite(v))
  if (xs.length === 0 || binCount < 1) return []

  const min = Math.min(...xs)
  const max = Math.max(...xs)
  if (min === max) return [{ from: min, to: max, count: xs.length }]

  const bins = Math.min(Math.floor(binCount), 100)
  const width = (max - min) / bins
  const out: Bin[] = Array.from({ length: bins }, (_, i) => ({
    from: min + i * width,
    to: min + (i + 1) * width,
    count: 0,
  }))
  for (const x of xs) {
    const index = x === max ? bins - 1 : Math.floor((x - min) / width)
    out[Math.max(0, Math.min(bins - 1, index))].count++
  }
  return out
}

/**
 * Sturges' rule, the default bin count.
 *
 * ceil(log2(n)) + 1 — the convention most spreadsheets use, so a reader
 * comparing this against Excel sees the same shape rather than wondering
 * which is wrong. Clamped to 1..50: below one there is no histogram, and
 * above fifty a bar is a hairline.
 */
export const suggestedBins = (n: number): number =>
  n < 2 ? 1 : Math.max(1, Math.min(50, Math.ceil(Math.log2(n)) + 1))

/* ──────────────────────────── tables ─────────────────────────── */

export interface Table {
  headers: string[]
  rows: string[][]
}

/**
 * The delimiter a file actually uses, sniffed from its first line.
 *
 * Counted OUTSIDE quoted fields, which is the whole difficulty:
 * `"Rossi, Mario";42` has more commas than semicolons and is a
 * semicolon file. Italian exports are semicolon-delimited far more often
 * than not, so getting this wrong is not an edge case here.
 */
export function sniffDelimiter(text: string): string {
  const firstLine = text.split(/\r?\n/, 1)[0] ?? ''
  const counts: Record<string, number> = { ',': 0, ';': 0, '\t': 0, '|': 0 }
  let inQuotes = false
  for (let i = 0; i < firstLine.length; i++) {
    const ch = firstLine[i]
    if (ch === '"') inQuotes = !inQuotes
    else if (!inQuotes && ch in counts) counts[ch]++
  }
  return Object.entries(counts).sort((a, b) => b[1] - a[1])[0][1] > 0
    ? Object.entries(counts).sort((a, b) => b[1] - a[1])[0][0]
    : ','
}

/**
 * RFC 4180-ish parse: quoted fields, doubled quotes as an escape, and
 * newlines INSIDE a quoted field.
 *
 * Written out rather than split on a delimiter, because the split
 * version works on every file until the first address column.
 */
export function parseDelimited(text: string, delimiter?: string): Table {
  const d = delimiter ?? sniffDelimiter(text)
  const rows: string[][] = []
  let row: string[] = []
  let field = ''
  let inQuotes = false

  const endField = (): void => {
    row.push(field)
    field = ''
  }
  const endRow = (): void => {
    endField()
    // A trailing newline must not produce a row of one empty string.
    if (row.length > 1 || row[0] !== '') rows.push(row)
    row = []
  }

  for (let i = 0; i < text.length; i++) {
    const ch = text[i]
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          field += '"'
          i++
        } else inQuotes = false
      } else field += ch
    } else if (ch === '"') inQuotes = true
    else if (ch === d) endField()
    else if (ch === '\n') endRow()
    else if (ch !== '\r') field += ch
  }
  if (field !== '' || row.length > 0) endRow()

  const [headers = [], ...body] = rows
  return { headers: headers.map((h) => h.trim()), rows: body }
}

/**
 * Merge tables by HEADER NAME, not by column position.
 *
 * Position-merging is the version everybody writes first, and it silently
 * puts July's revenue in June's cost column the moment one export has an
 * extra field. Here the union of headers is taken in first-seen order and
 * every row is re-indexed by name; a column a file does not have comes
 * through empty rather than shifting everything after it.
 */
export function mergeTables(tables: Table[]): Table {
  const headers: string[] = []
  for (const table of tables) {
    for (const header of table.headers) {
      if (header !== '' && !headers.includes(header)) headers.push(header)
    }
  }
  const rows: string[][] = []
  for (const table of tables) {
    const index = new Map(table.headers.map((h, i) => [h, i]))
    for (const row of table.rows) {
      rows.push(headers.map((h) => (index.has(h) ? (row[index.get(h)!] ?? '') : '')))
    }
  }
  return { headers, rows }
}

/** Back to CSV, quoting only the fields that need it. */
export function toCsv(table: Table, delimiter = ','): string {
  const cell = (value: string): string =>
    value.includes(delimiter) || value.includes('"') || /[\n\r]/.test(value)
      ? `"${value.replace(/"/g, '""')}"`
      : value
  return [table.headers, ...table.rows]
    .map((row) => row.map(cell).join(delimiter))
    .join('\n')
}

/** Columns whose values parse as numbers — the ones a chart can plot. */
export function numericColumns(table: Table): string[] {
  return table.headers.filter((header, i) => {
    const values = table.rows.map((r) => r[i]).filter((v) => v !== undefined && v.trim() !== '')
    if (values.length === 0) return false
    return values.every((v) => Number.isFinite(Number.parseFloat(v.replace(',', '.'))))
  })
}
