// Generated by electe-web/scripts/export-tools-repo.ts. Do not edit here: change the source in electe-migration and re-export.
// Source: electe-web/src/lib/tools/data.test.ts
import { describe, expect, it } from 'vitest'

import {
  histogram, mergeTables, numericColumns, parseDelimited, parseSeries,
  sniffDelimiter, suggestedBins, toCsv,
} from './data'

/**
 * The three ways a data tool loses somebody's data quietly.
 *
 * A histogram that drops its own maximum. A parser that splits an address
 * on the comma inside it. A merge that lines columns up by position and
 * puts July's revenue in June's cost column. None of the three throws,
 * none looks wrong on screen, and all three are the default behaviour of
 * the obvious implementation.
 */

describe('parseSeries', () => {
  it('takes commas, semicolons, spaces and newlines', () => {
    expect(parseSeries('1, 2;3\n4  5')).toEqual([1, 2, 3, 4, 5])
  })

  it('keeps negatives and decimals, drops words', () => {
    expect(parseSeries('-2.5, 3.75, total, 4')).toEqual([-2.5, 3.75, 4])
  })

  it('survives an empty paste', () => {
    expect(parseSeries('   ')).toEqual([])
  })
})

describe('histogram', () => {
  it('does not lose the maximum value', () => {
    // THE classic off-by-one. With half-open bins the largest value falls
    // outside every one of them and disappears from its own histogram —
    // invisible unless you add the counts up.
    const bins = histogram([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 5)
    expect(bins.reduce((n, b) => n + b.count, 0)).toBe(10)
    expect(bins.at(-1)?.count).toBeGreaterThan(0)
  })

  it('puts every value in exactly one bin', () => {
    const values = [3, 3, 3, 7, 7, 12, 18, 18, 18, 18, 25]
    for (const count of [2, 4, 7]) {
      const bins = histogram(values, count)
      expect(bins.reduce((n, b) => n + b.count, 0), `${count} bins`).toBe(values.length)
    }
  })

  it('gives a constant series one bin instead of dividing by zero', () => {
    const bins = histogram([5, 5, 5, 5], 6)
    expect(bins).toHaveLength(1)
    expect(bins[0].count).toBe(4)
  })

  it('produces bins of equal width, edge to edge', () => {
    const bins = histogram([0, 100], 4)
    expect(bins).toHaveLength(4)
    expect(bins[0].from).toBe(0)
    expect(bins.at(-1)?.to).toBe(100)
    for (const b of bins) expect(b.to - b.from).toBeCloseTo(25, 6)
  })

  it('returns nothing rather than throwing on empty input', () => {
    expect(histogram([], 5)).toEqual([])
    expect(histogram([1, 2, 3], 0)).toEqual([])
  })

  it('suggests bins by Sturges, clamped', () => {
    // ceil(log2 n) + 1 — what spreadsheets use, so a reader comparing
    // against Excel sees the same shape.
    expect(suggestedBins(100)).toBe(8)
    expect(suggestedBins(1)).toBe(1)
    expect(suggestedBins(1_000_000)).toBeLessThanOrEqual(50)
  })
})

describe('sniffDelimiter', () => {
  it('finds a semicolon file even when quoted fields hold commas', () => {
    // Italian exports are semicolon-delimited far more often than not,
    // and this line has more commas than semicolons.
    expect(sniffDelimiter('"Rossi, Mario";"Milano, MI";42')).toBe(';')
  })

  it('finds tabs and pipes', () => {
    expect(sniffDelimiter('a\tb\tc')).toBe('\t')
    expect(sniffDelimiter('a|b|c')).toBe('|')
  })

  it('falls back to a comma for a single column', () => {
    expect(sniffDelimiter('total')).toBe(',')
  })
})

describe('parseDelimited', () => {
  it('does not split on the comma inside a quoted field', () => {
    const t = parseDelimited('name,city\n"Rossi, Mario",Milano')
    expect(t.headers).toEqual(['name', 'city'])
    expect(t.rows).toEqual([['Rossi, Mario', 'Milano']])
  })

  it('handles a doubled quote as an escape', () => {
    const t = parseDelimited('quote\n"she said ""no"""')
    expect(t.rows[0][0]).toBe('she said "no"')
  })

  it('handles a newline inside a quoted field', () => {
    // The reason this is written out instead of split on the delimiter:
    // an address column breaks the split version on the first file.
    const t = parseDelimited('name,address\nRossi,"Via Roma 1\nMilano"')
    expect(t.rows).toHaveLength(1)
    expect(t.rows[0][1]).toBe('Via Roma 1\nMilano')
  })

  it('does not invent a row from a trailing newline', () => {
    expect(parseDelimited('a,b\n1,2\n').rows).toHaveLength(1)
  })

  it('reads CRLF files', () => {
    const t = parseDelimited('a,b\r\n1,2\r\n')
    expect(t.headers).toEqual(['a', 'b'])
    expect(t.rows).toEqual([['1', '2']])
  })
})

describe('mergeTables', () => {
  it('merges by header NAME, not by column position', () => {
    // The bug this exists to prevent: file two has an extra column, and
    // a positional merge puts its revenue under the other file's cost.
    const a = parseDelimited('month,revenue\nJan,100')
    const b = parseDelimited('month,region,revenue\nFeb,North,200')
    const merged = mergeTables([a, b])
    expect(merged.headers).toEqual(['month', 'revenue', 'region'])
    expect(merged.rows).toEqual([
      ['Jan', '100', ''],
      ['Feb', '200', 'North'],
    ])
  })

  it('leaves a missing column empty rather than shifting the row', () => {
    const merged = mergeTables([
      parseDelimited('a,b,c\n1,2,3'),
      parseDelimited('a,c\n4,6'),
    ])
    expect(merged.rows[1]).toEqual(['4', '', '6'])
  })

  it('keeps first-seen header order', () => {
    const merged = mergeTables([
      parseDelimited('z,a\n1,2'),
      parseDelimited('a,z\n3,4'),
    ])
    expect(merged.headers).toEqual(['z', 'a'])
    expect(merged.rows[1]).toEqual(['4', '3'])
  })

  it('merges nothing into nothing', () => {
    expect(mergeTables([])).toEqual({ headers: [], rows: [] })
  })
})

describe('toCsv', () => {
  it('round-trips a field containing the delimiter', () => {
    const table = { headers: ['name'], rows: [['Rossi, Mario']] }
    expect(parseDelimited(toCsv(table)).rows[0][0]).toBe('Rossi, Mario')
  })

  it('round-trips quotes and newlines', () => {
    const table = { headers: ['a'], rows: [['line\nbreak'], ['say "hi"']] }
    const back = parseDelimited(toCsv(table))
    expect(back.rows).toEqual(table.rows)
  })

  it('does not quote what does not need it', () => {
    expect(toCsv({ headers: ['a', 'b'], rows: [['1', '2']] })).toBe('a,b\n1,2')
  })
})

describe('numericColumns', () => {
  it('finds the columns a chart could plot', () => {
    const t = parseDelimited('month,revenue,note\nJan,100,ok\nFeb,200,fine')
    expect(numericColumns(t)).toEqual(['revenue'])
  })

  it('accepts a decimal comma', () => {
    const t = parseDelimited('v\n1,5\n2,5', ';')
    expect(numericColumns(t)).toEqual(['v'])
  })

  it('rejects a column that is numeric only sometimes', () => {
    const t = parseDelimited('v\n1\nn/a\n3')
    expect(numericColumns(t)).toEqual([])
  })
})
