// Generated by electe-web/scripts/export-tools-repo.ts from electe-migration@0754686 on 2026-09-29. Do not edit here: change the source and re-export.
/** The 21 locales of tools.electe.net, in the site's order. */
export const locales = [
  {
    "code": "en",
    "label": "English"
  },
  {
    "code": "it",
    "label": "Italiano"
  },
  {
    "code": "fr",
    "label": "Français"
  },
  {
    "code": "de",
    "label": "Deutsch"
  },
  {
    "code": "es",
    "label": "Español"
  },
  {
    "code": "pt",
    "label": "Português"
  },
  {
    "code": "zh",
    "label": "简体中文"
  },
  {
    "code": "tc",
    "label": "繁體中文"
  },
  {
    "code": "tr",
    "label": "Türkçe"
  },
  {
    "code": "ar",
    "label": "العربية"
  },
  {
    "code": "uk",
    "label": "Українська"
  },
  {
    "code": "vi",
    "label": "Tiếng Việt"
  },
  {
    "code": "th",
    "label": "ไทย"
  },
  {
    "code": "pl",
    "label": "Polski"
  },
  {
    "code": "he",
    "label": "עברית"
  },
  {
    "code": "id",
    "label": "Bahasa Indonesia"
  },
  {
    "code": "nl",
    "label": "Nederlands"
  },
  {
    "code": "sv",
    "label": "Svenska"
  },
  {
    "code": "ro",
    "label": "Română"
  },
  {
    "code": "ko",
    "label": "한국어"
  },
  {
    "code": "ja",
    "label": "日本語"
  }
] as const

export const localeCodes: string[] = locales.map((l) => l.code)
export const defaultLocale = "en"
