// Generated by electe-web/scripts/export-tools-repo.ts. Do not edit here: change the source in electe-migration and re-export.
// Source: electe-web/src/lib/tools/registry.test.ts
import { describe, expect, it } from 'vitest'

import { CATEGORIES, slugFor, TOOLS, toolBySlug, type ToolDef } from './registry'

/**
 * THE FORMULAS, checked against worked examples rather than against
 * themselves.
 *
 * These calculators are replacing a vendor's. Nobody will notice a wrong
 * one: the page renders, a number appears, and it is plausible. The old
 * ROI tool is the proof — its two fields ("Initial Investment", "Net
 * Profit from Investment") admit two readings that differ by exactly 100
 * percentage points, and no test anywhere could tell you which it meant.
 *
 * So each case below states a scenario with an answer someone can check
 * by hand, not `compute(x)` compared to a rearrangement of `compute`.
 */

const tool = (id: string): ToolDef => {
  const t = TOOLS.find((x) => x.id === id)
  if (!t) throw new Error(`no tool ${id}`)
  return t
}
/**
 * A tool's formula, asserted to exist.
 *
 * `ToolDef.compute` became optional when the twelve `custom` tools
 * joined the registry — they render a chart or call a model and have no
 * formula to state. Every id this file names is a calculator, so a
 * missing formula here is a registry bug, not a case to branch on.
 */
const formula = (id: string): NonNullable<ToolDef['compute']> => {
  const t = tool(id)
  if (!t.compute) throw new Error(`tool ${id} has no formula`)
  return t.compute
}
const run = (id: string, values: Record<string, unknown>) =>
  formula(id)(values as Record<string, number | undefined>)

describe('finance', () => {
  it('ROI: 10,000 in, 12,500 back is 25%, not 125%', () => {
    // The ambiguity the old tool shipped. 2,500 of gain on 10,000 is a
    // 25% return; reading the second field as "profit already net"
    // would give 125% and look just as reasonable on screen.
    expect(run('roi', { investment: 10000, returned: 12500 })).toEqual({ roi: 0.25, netGain: 2500 })
  })

  it('ROI: a loss is negative, not absolute', () => {
    expect(run('roi', { investment: 10000, returned: 7000 })).toEqual({ roi: -0.3, netGain: -3000 })
  })

  it('ROI: zero investment yields null, never Infinity', () => {
    expect(run('roi', { investment: 0, returned: 500 }).roi).toBeNull()
  })

  it('NPV: 5 years of 15,000 at 8% against 50,000', () => {
    // PV of a 5-year 15,000 annuity at 8% = 15000 × 3.99271 = 59,890.65
    const r = run('npv', { investment: 50000, cashflow: 15000, years: 5, rate: 8 })
    expect(r.discounted).toBeCloseTo(59890.65, 1)
    expect(r.npv).toBeCloseTo(9890.65, 1)
    expect(r.payback).toBeCloseTo(3.33, 2)
  })

  it('NPV: a zero discount rate is just the undiscounted sum', () => {
    const r = run('npv', { investment: 1000, cashflow: 500, years: 4, rate: 0 })
    expect(r.discounted).toBe(2000)
    expect(r.npv).toBe(1000)
  })

  it('gross margin distinguishes margin from markup', () => {
    // 100k revenue, 60k COGS: margin 40% of revenue, markup 66.67% of cost.
    // Quoting one as the other is the most common pricing error there is.
    const r = run('gross-margin', { revenue: 100000, cogs: 60000 })
    expect(r.marginPct).toBe(0.4)
    expect(r.markupPct).toBeCloseTo(0.6667, 3)
    expect(r.grossProfit).toBe(40000)
  })

  it('break-even: 40,000 fixed at 35 contribution needs 1,143 units', () => {
    // 40000 / (90 − 55) = 1142.86 → 1143, rounded UP: 1142 units does
    // not break even, and a calculator that floors here is wrong.
    const r = run('break-even', { fixedCosts: 40000, price: 90, variableCost: 55 })
    expect(r.contributionPerUnit).toBe(35)
    expect(r.breakEvenUnits).toBe(1143)
    expect(r.breakEvenRevenue).toBe(102870)
  })

  it('break-even: selling at or below variable cost never breaks even', () => {
    const r = run('break-even', { fixedCosts: 40000, price: 50, variableCost: 55 })
    expect(r.breakEvenUnits).toBeNull()
    expect(r.contributionPerUnit).toBe(-5)
  })

  it('investment simulator: contributions are end-of-period', () => {
    // 0 initial, 100/month, 1 year, 0% return → exactly 1,200 and no growth.
    const flat = run('investment-simulator', { initial: 0, monthly: 100, years: 1, returnRate: 0 })
    expect(flat.finalValue).toBe(1200)
    expect(flat.growth).toBe(0)
    // With a return, the last contribution earns nothing (ordinary annuity).
    const grown = run('investment-simulator', { initial: 1000, monthly: 0, years: 10, returnRate: 7 })
    expect(grown.finalValue).toBeCloseTo(1967.15, 0)
  })

  it('investment simulator: fees come off the return, inflation off the result', () => {
    const r = run('investment-simulator', {
      initial: 10000, monthly: 0, years: 10, returnRate: 7, fees: 1, inflation: 2,
    })
    // 6% net nominal for 10 years, then deflated at 2%.
    expect(r.finalValue).toBeCloseTo(17908.48, 0)
    expect(r.realValue).toBeCloseTo(14691.19, 0) // 17908.48 / 1.02^10
  })

  it('net invested capital excludes cash from operating assets', () => {
    const r = run('net-invested-capital', {
      fixedAssets: 400000, operatingAssets: 250000, operatingLiabilities: 120000, cash: 60000,
    })
    expect(r.workingCapital).toBe(70000)
    expect(r.nic).toBe(470000)
  })

  it('reverse factoring prices on actual/365', () => {
    // 500,000 at 4.5% for 60 days = 500000 × 0.045 × 60/365 = 3,698.63
    const r = run('reverse-factoring', { invoiceValue: 500000, extensionDays: 60, discountRate: 4.5 })
    expect(r.financingCost).toBeCloseTo(3698.63, 1)
    expect(r.netToSupplier).toBeCloseTo(496301.37, 1)
  })

  it('profitability: operating profit and ROA', () => {
    const r = run('profitability', {
      revenue: 1000000, cogs: 600000, operatingExpenses: 250000, totalAssets: 750000,
    })
    expect(r.grossMarginPct).toBe(0.4)
    expect(r.operatingProfit).toBe(150000)
    expect(r.netMarginPct).toBe(0.15)
    expect(r.roa).toBe(0.2)
  })
})

describe('inventory', () => {
  it('reorder point: demand × lead time + safety stock', () => {
    const r = run('reorder-point', { dailyDemand: 40, leadTime: 7, safetyStock: 60 })
    expect(r.leadTimeDemand).toBe(280)
    expect(r.reorderPoint).toBe(340)
  })

  it('reorder point rounds UP — you cannot order a third of a unit late', () => {
    expect(run('reorder-point', { dailyDemand: 12.5, leadTime: 3 }).reorderPoint).toBe(38)
  })

  it('reorder point: safety stock is genuinely optional', () => {
    expect(run('reorder-point', { dailyDemand: 40, leadTime: 7 }).reorderPoint).toBe(280)
  })

  it('inventory turnover and its days are consistent with each other', () => {
    const r = run('inventory-turnover', { cogs: 900000, averageInventory: 150000 })
    expect(r.turnover).toBe(6)
    expect(r.daysOfInventory).toBeCloseTo(60.8, 1)
  })

  it('days inventory on hand agrees with turnover on the same numbers', () => {
    const r = run('days-inventory', { averageInventory: 150000, cogs: 900000, periodDays: 365 })
    expect(r.dio).toBeCloseTo(60.8, 1)
    expect(r.turnover).toBe(6)
  })

  it('sell-through above 100% is reported, not clamped', () => {
    // Returns and backorders make this real; clamping hides a data issue.
    const r = run('sell-through', { unitsReceived: 100, unitsSold: 110 })
    expect(r.sellThrough).toBe(1.1)
    expect(r.unitsRemaining).toBe(-10)
  })
})

describe('sales', () => {
  it('AOV divides revenue by orders', () => {
    expect(run('aov', { revenue: 84000, orders: 1200 }).aov).toBe(70)
  })

  it('AOV with zero orders is null, not Infinity', () => {
    expect(run('aov', { revenue: 84000, orders: 0 }).aov).toBeNull()
  })

  it('conversion rate, and what a lead is worth', () => {
    // 84 of 2,400 is 3.5%, not 4%. This expectation said 0.04 while the
    // code still rounded fractions to two places — the test had encoded
    // the rounding bug rather than caught it, which is what a worked
    // example is supposed to prevent. Rounding a CONVERSION RATE to the
    // nearest whole percent is the difference between 3.5% and 4%, and a
    // 14% overstatement of pipeline efficiency.
    const r = run('conversion-rate', { conversions: 84, total: 2400, revenue: 42000 })
    expect(r.conversionRate).toBe(0.035)
    expect(r.revenuePerLead).toBe(17.5)
    expect(r.valuePerConversion).toBe(500)
  })

  it('CLV: simple form, and the margin form beside it', () => {
    const r = run('customer-lifetime-value', {
      averageOrderValue: 70, purchasesPerYear: 4, yearsRetained: 3, grossMargin: 60,
    })
    expect(r.annualValue).toBe(280)
    expect(r.clv).toBe(840)
    expect(r.marginClv).toBe(504)
  })

  it('churn DERIVES losses so the numbers on screen cannot contradict', () => {
    // 1000 start, 120 won, 960 end → 160 lost, 16% churn. Asking for the
    // churned count directly lets a reader enter 40 and be quietly wrong.
    const r = run('churn-rate', { customersStart: 1000, customersEnd: 960, customersAcquired: 120 })
    expect(r.churnedCustomers).toBe(160)
    expect(r.churnRate).toBe(0.16)
    expect(r.retentionRate).toBe(0.84)
  })

  it('churn without acquisitions is the plain start-to-end drop', () => {
    const r = run('churn-rate', { customersStart: 200, customersEnd: 180 })
    expect(r.churnedCustomers).toBe(20)
    expect(r.churnRate).toBe(0.1)
  })

  it('percentage discount', () => {
    const r = run('percentage-discount', { originalPrice: 249, discountPercent: 20 })
    expect(r.saving).toBe(49.8)
    expect(r.finalPrice).toBe(199.2)
  })
})

describe('marketing', () => {
  it('NPS counts passives in the denominator and nowhere else', () => {
    // 240/120/40 of 400 → 60% − 10% = +50. Dropping passives entirely
    // would give +71.4, which is the classic mistake.
    const r = run('nps', { promoters: 240, passives: 120, detractors: 40 })
    expect(r.responses).toBe(400)
    expect(r.nps).toBe(50)
    expect(r.promoterPct).toBe(0.6)
    expect(r.detractorPct).toBe(0.1)
  })

  it('NPS spans −100 to +100', () => {
    expect(run('nps', { promoters: 0, passives: 0, detractors: 10 }).nps).toBe(-100)
    expect(run('nps', { promoters: 10, passives: 0, detractors: 0 }).nps).toBe(100)
  })

  it('NPS with no responses is null, not 0 — they are different answers', () => {
    const r = run('nps', { promoters: 0, passives: 0, detractors: 0 })
    expect(r.nps).toBeNull()
    expect(r.responses).toBe(0)
  })
})

describe('operations', () => {
  it('productivity per employee and per hour', () => {
    const r = run('employee-productivity', {
      output: 800000, employees: 10, hoursPerEmployee: 1600, labourCost: 400000,
    })
    expect(r.perEmployee).toBe(80000)
    expect(r.perHour).toBe(50)
    expect(r.labourRatio).toBe(2)
  })

  it('renovation cost compounds uplift and contingency, not adds them', () => {
    // 90 × 750 = 67,500 → ×1.25 → 84,375 → ×1.10 = 92,812.50.
    // Adding 35% instead would give 91,125 — close enough to look right.
    const r = run('renovation-cost', {
      squareMetres: 90, ratePerSqm: 750, systemsUpliftPct: 25, contingencyPct: 10,
    })
    expect(r.baseCost).toBe(67500)
    expect(r.total).toBe(92812.5)
    expect(r.effectivePerSqm).toBe(1031.25)
  })

  it('shipping charges the GREATER of volumetric and actual weight', () => {
    // 40×30×20 / 5000 = 4.8 kg volumetric against 3.5 kg actual.
    const light = run('shipping-cost', {
      lengthCm: 40, widthCm: 30, heightCm: 20, actualWeightKg: 3.5, ratePerKg: 4.2,
    })
    expect(light.volumetricWeight).toBe(4.8)
    expect(light.chargeableWeight).toBe(4.8)
    expect(light.shippingCost).toBeCloseTo(20.16, 2)
    // A dense parcel is charged on its actual weight instead.
    const dense = run('shipping-cost', {
      lengthCm: 20, widthCm: 20, heightCm: 20, actualWeightKg: 9, ratePerKg: 4.2,
    })
    expect(dense.chargeableWeight).toBe(9)
  })

  it('cost-benefit: BCR above 1 means the benefits carry the costs', () => {
    const r = run('cost-benefit', {
      upfrontCost: 60000, annualCost: 8000, annualBenefit: 32000, years: 5, rate: 6,
    })
    expect(r.pvBenefits).toBeCloseTo(134795.64, 0) // 32000 x 4.212364
    expect(r.pvCosts).toBeCloseTo(93698.91, 0)
    expect(r.bcr).toBeCloseTo(1.44, 2)
    expect(r.netBenefit).toBeCloseTo(41096.73, 0)
  })

  it('KPI attainment handles a baseline, and a zero range without dividing', () => {
    const r = run('kpi-attainment', { actual: 84, target: 100, baseline: 60 })
    expect(r.attainment).toBe(0.84)
    expect(r.gap).toBe(16)
    expect(r.progressFromBaseline).toBe(0.6)
    expect(run('kpi-attainment', { actual: 5, target: 5, baseline: 5 }).progressFromBaseline).toBeNull()
  })

  it('domestic-worker holiday: 26 days full-time, pro-rated by hours', () => {
    // The CCNL figure. Half-time for a full year is half of it.
    expect(run('domestic-worker-holiday', { hoursPerWeek: 40, monthsWorked: 12 }).holidayDays).toBe(26)
    expect(run('domestic-worker-holiday', { hoursPerWeek: 20, monthsWorked: 12 }).holidayDays).toBe(13)
    expect(run('domestic-worker-holiday', { hoursPerWeek: 20, monthsWorked: 6 }).holidayDays).toBe(6.5)
  })

  it('domestic-worker holiday never exceeds full time on overtime', () => {
    // 50 hours a week does not earn 32.5 days.
    expect(run('domestic-worker-holiday', { hoursPerWeek: 50, monthsWorked: 12 }).holidayDays).toBe(26)
  })
})

describe('data', () => {
  it('variance returns BOTH conventions, so n−1 vs n is visible', () => {
    // [2,4,4,4,5,5,7,9]: mean 5, population variance 4, sample 4.571.
    const r = formula('variance')({ series: [2, 4, 4, 4, 5, 5, 7, 9] } as never)
    expect(r.mean).toBe(5)
    expect(r.populationVariance).toBe(4)
    expect(r.sampleVariance).toBeCloseTo(4.5714, 3)
    expect(r.sampleStdDev).toBeCloseTo(2.138, 3)
    expect(r.count).toBe(8)
  })

  it('variance of a single point has no sample variance', () => {
    const r = formula('variance')({ series: [7] } as never)
    expect(r.populationVariance).toBe(0)
    expect(r.sampleVariance).toBeNull()
  })

  it('variance of nothing is null, not zero', () => {
    expect(formula('variance')({ series: [] } as never).sampleVariance).toBeNull()
  })
})

describe('reclassification and lease', () => {
  it('reclassifies a balance sheet into the four margins', () => {
    const r = run('balance-sheet-reclassification', {
      fixedAssets: 380000, inventory: 90000, receivables: 140000, cash: 45000,
      equity: 300000, shortTermDebt: 210000, longTermDebt: 145000,
    })
    // Current assets 275,000 against 210,000 of short-term debt.
    expect(r.currentAssets).toBe(275000)
    expect(r.workingCapital).toBe(65000)
    // Treasury margin drops the stock: 185,000 − 210,000 = −25,000. The
    // business is only liquid if it sells inventory, which is exactly
    // what working capital alone hides.
    expect(r.treasuryMargin).toBe(-25000)
    // Equity 300,000 against 380,000 of fixed assets — the long-term
    // investment is not fully covered by own funds.
    expect(r.structuralMargin).toBe(-80000)
    expect(r.currentRatio).toBeCloseTo(1.31, 2)
    expect(r.debtToEquity).toBeCloseTo(1.18, 2)
  })

  it('treasury margin and working capital differ by exactly the inventory', () => {
    // The property that makes the second figure worth showing at all.
    const v = {
      fixedAssets: 100000, inventory: 50000, receivables: 40000, cash: 10000,
      equity: 120000, shortTermDebt: 60000, longTermDebt: 20000,
    }
    const r = run('balance-sheet-reclassification', v)
    expect((r.workingCapital as number) - (r.treasuryMargin as number)).toBe(v.inventory)
  })

  it('business lease prices rent on assets and checks it against earnings', () => {
    const r = run('business-lease', {
      assetValue: 450000, revenue: 620000, operatingCosts: 540000, yieldPct: 7,
    })
    expect(r.ebitda).toBe(80000)
    expect(r.annualRent).toBe(31500)
    expect(r.monthlyRent).toBe(2625)
    // 31,500 of 80,000 — the rent takes 39% of the earnings, which is
    // the number a first-time lessee never works out.
    expect(r.rentToEbitda).toBeCloseTo(0.3938, 3)
    expect(r.residualToTenant).toBe(48500)
  })

  it('business lease reports no ratio rather than a negative one', () => {
    // A loss-making business has no meaningful "rent as a share of
    // EBITDA"; "−140%" is not a sentence that helps anybody.
    const r = run('business-lease', {
      assetValue: 450000, revenue: 500000, operatingCosts: 520000, yieldPct: 7,
    })
    expect(r.ebitda).toBe(-20000)
    expect(r.rentToEbitda).toBeNull()
    expect(r.residualToTenant).toBe(-51500)
  })
})

describe('sales forecast', () => {
  const forecast = (series: number[], extra: Record<string, unknown> = {}) =>
    formula('sales-forecast')({ series, periodsAhead: 3, ...extra } as never)

  it('continues a perfectly linear series exactly', () => {
    // 10, 20, 30, 40, 50 has level 50 and trend 10 under any smoothing
    // constants, because there is no noise for them to smooth.
    const r = forecast([10, 20, 30, 40, 50])
    expect(r.trend).toBeCloseTo(10, 1)
    expect(r.next).toBeCloseTo(60, 1)
    // 60 + 70 + 80
    expect(r.total).toBeCloseTo(210, 1)
    expect(r.periods).toBe(5)
  })

  it('projects a flat series flat', () => {
    const r = forecast([100, 100, 100, 100])
    expect(r.trend).toBeCloseTo(0, 2)
    expect(r.next).toBeCloseTo(100, 1)
  })

  it('follows a decline downward', () => {
    const r = forecast([100, 90, 80, 70])
    expect(r.trend as number).toBeLessThan(0)
    expect(r.next as number).toBeLessThan(70)
  })

  it('needs two points before it will guess at a trend', () => {
    expect(forecast([42]).next).toBeNull()
    expect(forecast([]).next).toBeNull()
  })

  it('clamps smoothing constants instead of diverging', () => {
    // alpha outside (0,1] does not make a slower forecast, it makes a
    // divergent one. Both of these fall back to the defaults.
    for (const alpha of [0, -1, 5]) {
      const r = forecast([10, 20, 30, 40, 50], { alpha })
      expect(Number.isFinite(r.next as number)).toBe(true)
      expect(r.next).toBeCloseTo(60, 0)
    }
  })

  it('returns nothing for a zero horizon rather than an empty sum', () => {
    expect(forecast([10, 20, 30], { periodsAhead: 0 }).total).toBeNull()
  })
})

describe('the registry itself', () => {
  it('never returns NaN or Infinity, whatever it is given', () => {
    // The property that matters most: a calculator printing "NaN" or "∞"
    // has told the reader something false about their business. Every
    // tool, every degenerate input.
    const nasty = [undefined, 0, -1, Number.NaN, Number.POSITIVE_INFINITY]
    for (const t of TOOLS) {
      if (!t.compute) continue // a `custom` tool: no formula to fuzz
      for (const bad of nasty) {
        const values = Object.fromEntries(t.inputs.map((i) => [i.key, bad as number]))
        for (const [key, value] of Object.entries(t.compute(values))) {
          expect(
            value === null || Number.isFinite(value),
            `${t.id}.${key} returned ${value} for input ${String(bad)}`,
          ).toBe(true)
        }
      }
    }
  })

  it('gives every numeric tool exactly one primary output', () => {
    // The nine `llm` tools answer in prose: no output is a number, so
    // there is no headline figure to mark. Every other tool has one, and
    // "exactly one" is the point — two primaries render two large
    // numbers and the reader has to guess which is the answer.
    for (const t of TOOLS) {
      if (t.custom === 'llm') {
        expect(t.outputs, `${t.id} answers in prose and should declare no outputs`).toEqual([])
        continue
      }
      expect(t.outputs.filter((o) => o.primary), `${t.id}`).toHaveLength(1)
    }
  })

  it('gives every tool a formula unless it is a custom one', () => {
    // `ToolDef.compute` is optional only so the twelve custom tools can
    // omit it. Anything the generic Calculator renders must have one, or
    // the page throws at render time instead of failing here.
    const missing = TOOLS.filter((t) => !t.custom && !t.compute).map((t) => t.id)
    expect(missing, `tools with no formula and no custom renderer: ${missing.join(', ')}`).toEqual(
      [],
    )
  })

  it('has no duplicate slug in any locale', () => {
    // Two tools sharing a slug is a route that serves whichever the
    // finder reaches first — silently, and differently per locale.
    const seen = new Set<string>()
    for (const t of TOOLS) {
      for (const [locale, slug] of Object.entries(t.slugs)) {
        const key = `${locale}:${slug}`
        expect(seen.has(key), `duplicate slug ${key}`).toBe(false)
        seen.add(key)
      }
    }
  })

  it('has no duplicate tool id', () => {
    expect(new Set(TOOLS.map((t) => t.id)).size).toBe(TOOLS.length)
  })

  it('gives every tool an English slug — it is the fallback', () => {
    for (const t of TOOLS) expect(typeof t.slugs.en, t.id).toBe('string')
  })

  it('resolves a slug in its own locale and falls back to English', () => {
    expect(toolBySlug('it', 'punto-di-riordino')?.id).toBe('reorder-point')
    expect(toolBySlug('en', 'reorder-point-calculator')?.id).toBe('reorder-point')
    // A locale with no slug of its own still resolves via English.
    expect(toolBySlug('de', 'reorder-point-calculator')?.id).toBe('reorder-point')
    expect(toolBySlug('it', 'no-such-tool')).toBeUndefined()
  })

  it('slugFor falls back to English rather than returning undefined', () => {
    // This used to use 'ja' as the no-slug locale. All 21 are covered since
    // the slug fill, so the fallback now needs a locale that genuinely has
    // none — otherwise the test passes by asserting a real Japanese slug and
    // stops testing the fallback at all.
    const t = tool('reorder-point')
    expect(slugFor(t, 'it')).toBe('punto-di-riordino')
    expect(slugFor(t, 'ja')).toBe('発注点計算ツール')
    expect(slugFor(t, 'xx')).toBe('reorder-point-calculator')
  })

  it('only uses categories the index page knows how to render', () => {
    for (const t of TOOLS) expect(CATEGORIES).toContain(t.category)
  })

  it('gives every input a placeholder, so no field is a blank stare', () => {
    for (const t of TOOLS) {
      for (const i of t.inputs) {
        expect(typeof i.placeholder, `${t.id}.${i.key}`).toBe('number')
      }
    }
  })
})
