// Generated by electe-web/scripts/export-tools-repo.ts from electe-migration@0754686 on 2026-09-29. Do not edit here: change the source and re-export.
// Source: electe-web/src/lib/tools/registry.ts
/**
 * The tools catalogue — one typed definition per calculator.
 *
 * WHY THIS EXISTS AT ALL. tools.electe.net was Outrank.so's hosted
 * SEO-tools product: their infrastructure, their React bundle, 44 indexed
 * pages whose lifecycle is tied to our subscription. The architecture log
 * has flagged that as a silent dependency since July — "cancelling Outrank
 * kills these indexed pages". Most of what it hosts is arithmetic a
 * browser can do in a microsecond: a reorder point is average demand times
 * lead time plus safety stock. There was never a reason for a vendor to
 * own that, or for those URLs to depend on a renewal.
 *
 * SO THE FORMULAS ARE WRITTEN OUT HERE, not reverse-engineered. The live
 * calculators are a minified bundle, and lifting arithmetic out of
 * minified JS gets you something that matches the artefact rather than the
 * definition — where those two differ, the definition is right and the
 * artefact is a bug to inherit. Every `compute` below is the textbook
 * formula, stated in the doc comment, with the source convention named
 * where more than one exists.
 *
 * WHAT IS NOT HERE. Fourteen of the 43 are LLM- or upload-backed —
 * cost analysis, sales forecasting, company profiles, risk scoring. Those
 * need the platform's LLM lane and a file pipeline, they are a separate
 * piece of work, and their URLs are held in `deferred.ts` so nothing in
 * the sitemap or the redirect map forgets they exist.
 *
 * SLUGS ARE PER LOCALE, which is the repo's first non-negotiable and also
 * what makes this migration lossless. Several tools already existed TWICE
 * on the old host under an English and an Italian slug —
 * `reorder-point-calculator` and `punto-di-riordino` are the same
 * calculator — so they collapse into one tool with two slugs rather than
 * two pages competing for the same query.
 */

/** A field the reader fills in. */
import { LOCALE_SLUGS } from './slugs.generated'

export interface ToolInput {
  /** Stable key: the message-catalog key and the compute argument name. */
  key: string
  /** number | percent | integer — decides the control and the validation. */
  kind: 'number' | 'percent' | 'integer'
  /** Optional inputs may be left blank; compute receives undefined. */
  optional?: boolean
  /** Lower bound the UI enforces. Most business quantities cannot be negative. */
  min?: number
  /** Shown greyed in the field. Not a default — an empty field stays empty. */
  placeholder?: number
}

/** One number the calculator returns. */
export interface ToolOutput {
  key: string
  /** How to render it. `currency` is symbol-less — the reader's own unit. */
  format: 'number' | 'currency' | 'percent' | 'integer' | 'days'
  /** The headline result, rendered large. Exactly one per tool. */
  primary?: boolean
}

export type ToolValues = Record<string, number | undefined>
export type ToolResult = Record<string, number | null>

export interface ToolDef {
  /** Stable id — the message-catalog namespace, never a URL. */
  id: string
  /** Per-locale slug. `en` is required; any locale may add its own. */
  slugs: Record<string, string>
  /** Grouping on the index page. */
  category: 'finance' | 'inventory' | 'sales' | 'marketing' | 'operations' | 'data'
  /**
   * Takes a pasted number series in addition to (or instead of) fields.
   *
   * This used to be inferred from `inputs.length === 0`, which was true
   * while `variance` was the only series tool and wrong the moment one
   * needed both — a forecast wants the history AND how many periods to
   * project. Inference that holds for exactly one case is a coincidence,
   * not a rule.
   */
  series?: boolean
  /**
   * Renders a bespoke component instead of the generic `Calculator`.
   *
   * Three of these are not calculators — they take a table or a series
   * and hand back a chart or a file, so "fields in, numbers out" does
   * not describe them. They stay in this registry anyway, because the
   * registry is what owns slugs, categories and copy keys; only the body
   * of the page differs.
   */
  custom?: 'histogram' | 'csv-merge' | 'data-viz' | 'llm'
  /**
   * Message keys a custom component asks for that nothing else can
   * derive — button labels, hints, error strings.
   *
   * The generic pages get their keys from `inputs` and `outputs`, so the
   * catalog test can check them from the registry alone. A bespoke
   * component's strings are invisible to that, and a missing one ships
   * as a blank button. Listing them here keeps one source of truth
   * rather than a second list inside the test.
   */
  extraKeys?: string[]
  inputs: ToolInput[]
  outputs: ToolOutput[]
  /**
   * The maths. Pure, synchronous, and total: it returns `null` for an
   * output it cannot compute (a missing input, a division by zero) rather
   * than NaN or Infinity, because a calculator that prints "NaN" or "∞"
   * has told the reader something false about their business.
   *
   * OPTIONAL ONLY FOR `custom` TOOLS, and `registry.test.ts` enforces
   * that. A tool the generic `Calculator` renders has arithmetic behind
   * it by definition; the nine LLM tools and the three data tools have
   * no formula to state, and nine `() => ({})` stubs among 32 real
   * formulas would make the file lie about what it contains.
   */
  compute?: (v: ToolValues) => ToolResult
  /** How many FAQ entries this tool's catalog block carries. */
  faqs: number
}

/* ─────────────────────────── helpers ─────────────────────────── */

/** A finite number, or undefined. Guards every formula below. */
const n = (x: number | undefined): number | undefined =>
  typeof x === 'number' && Number.isFinite(x) ? x : undefined

/** Divide, or null. The single reason this file has no Infinity in it. */
const div = (a: number | undefined, b: number | undefined): number | null =>
  n(a) !== undefined && n(b) !== undefined && b !== 0 ? (a as number) / (b as number) : null

/** Round to `places`, preserving null. */
const round = (x: number | null, places = 2): number | null =>
  x === null ? null : Math.round(x * 10 ** places) / 10 ** places

/**
 * A ratio destined for a `percent` output, kept to FOUR decimal places.
 *
 * Percentages are stored here as fractions and multiplied by 100 at
 * render, so the default two places is only two SIGNIFICANT digits once
 * it reaches the screen: a 66.67% markup rounded to 0.67 renders as
 * "67%". Caught by the worked example in the test, which is the whole
 * reason that example uses a number with a repeating decimal.
 */
const pct = (x: number | null): number | null => round(x, 4)

/**
 * The authored tools. `TOOLS` below is this list with the 19 generated
 * locale slugs merged in — see `slugs.generated.ts`. Only `en` and `it` are
 * written by hand here, because those two are the locales with indexed URLs
 * on the live property.
 */
const AUTHORED_TOOLS: ToolDef[] = [
  /* ───────────────────────── finance ───────────────────────── */
  {
    // ROI = (net profit − investment) / investment.
    //
    // THE CONVENTION MATTERS and the old page got it ambiguous. Its two
    // fields were "Initial Investment" and "Net Profit from Investment",
    // which reads either as profit ALREADY NET of the investment (so ROI
    // = profit / investment) or as gross return (so ROI = (return −
    // investment) / investment). Those differ by exactly 100 points.
    // Here the field is the total AMOUNT RETURNED, the subtraction is
    // explicit, and the net gain is shown as its own output so the
    // reader can see which number the percentage came from.
    id: 'roi',
    slugs: { en: 'roi-calculator', it: 'calcolo-ritorno-investimento' },
    category: 'finance',
    inputs: [
      { key: 'investment', kind: 'number', min: 0, placeholder: 10000 },
      { key: 'returned', kind: 'number', min: 0, placeholder: 12500 },
    ],
    outputs: [
      { key: 'roi', format: 'percent', primary: true },
      { key: 'netGain', format: 'currency' },
    ],
    compute: ({ investment, returned }) => ({
      roi: pct(div(n(returned) !== undefined && n(investment) !== undefined
        ? (returned as number) - (investment as number) : undefined, investment)),
      netGain: n(returned) !== undefined && n(investment) !== undefined
        ? round((returned as number) - (investment as number)) : null,
    }),
    faqs: 4,
  },
  {
    // NPV = Σ cashflow_t / (1+r)^t − initial investment.
    // Flat annual cash flow, because a per-period grid is a spreadsheet
    // and this is a calculator; the payback line is what most readers
    // actually came for.
    id: 'npv',
    slugs: { en: 'npv-calculator', it: 'calcolo-valore-attuale-netto' },
    category: 'finance',
    inputs: [
      { key: 'investment', kind: 'number', min: 0, placeholder: 50000 },
      { key: 'cashflow', kind: 'number', placeholder: 15000 },
      { key: 'years', kind: 'integer', min: 1, placeholder: 5 },
      { key: 'rate', kind: 'percent', placeholder: 8 },
    ],
    outputs: [
      { key: 'npv', format: 'currency', primary: true },
      { key: 'discounted', format: 'currency' },
      { key: 'payback', format: 'number' },
    ],
    compute: ({ investment, cashflow, years, rate }) => {
      const I = n(investment), C = n(cashflow), Y = n(years), R = n(rate)
      if (I === undefined || C === undefined || Y === undefined || R === undefined || Y < 1) {
        return { npv: null, discounted: null, payback: null }
      }
      const r = R / 100
      let pv = 0
      for (let t = 1; t <= Math.floor(Y); t++) pv += C / (1 + r) ** t
      return {
        discounted: round(pv),
        npv: round(pv - I),
        // Undiscounted payback, the conventional headline. Null when the
        // flow never repays rather than a misleading large number.
        payback: C > 0 ? round(I / C) : null,
      }
    },
    faqs: 4,
  },
  {
    // Gross margin % = (revenue − COGS) / revenue. Margin, not markup —
    // the two are confused constantly and the tool names both.
    id: 'gross-margin',
    slugs: { en: 'gross-margin-calculator', it: 'calcolo-margine-lordo' },
    category: 'finance',
    inputs: [
      { key: 'revenue', kind: 'number', min: 0, placeholder: 100000 },
      { key: 'cogs', kind: 'number', min: 0, placeholder: 62000 },
    ],
    outputs: [
      { key: 'marginPct', format: 'percent', primary: true },
      { key: 'grossProfit', format: 'currency' },
      { key: 'markupPct', format: 'percent' },
    ],
    compute: ({ revenue, cogs }) => {
      const R = n(revenue), C = n(cogs)
      if (R === undefined || C === undefined) return { marginPct: null, grossProfit: null, markupPct: null }
      return {
        grossProfit: round(R - C),
        marginPct: pct(div(R - C, R)),
        markupPct: pct(div(R - C, C)),
      }
    },
    faqs: 3,
  },
  {
    // Profit = revenue − variable − fixed, with the margin alongside.
    id: 'profit',
    slugs: { en: 'profit-calculator', it: 'calcolo-profitto' },
    category: 'finance',
    inputs: [
      { key: 'revenue', kind: 'number', min: 0, placeholder: 250000 },
      { key: 'variableCosts', kind: 'number', min: 0, placeholder: 120000 },
      { key: 'fixedCosts', kind: 'number', min: 0, placeholder: 70000 },
    ],
    outputs: [
      { key: 'netProfit', format: 'currency', primary: true },
      { key: 'contributionMargin', format: 'currency' },
      { key: 'netMarginPct', format: 'percent' },
    ],
    compute: ({ revenue, variableCosts, fixedCosts }) => {
      const R = n(revenue), V = n(variableCosts), F = n(fixedCosts)
      if (R === undefined || V === undefined || F === undefined) {
        return { netProfit: null, contributionMargin: null, netMarginPct: null }
      }
      return {
        contributionMargin: round(R - V),
        netProfit: round(R - V - F),
        netMarginPct: pct(div(R - V - F, R)),
      }
    },
    faqs: 3,
  },
  {
    // Break-even units = fixed / (price − variable per unit).
    // Contribution margin ≤ 0 is not an error, it is the answer: no
    // volume ever breaks even, and the tool says so instead of dividing.
    id: 'break-even',
    slugs: { en: 'break-even-calculator', it: 'calcolo-punto-di-pareggio' },
    category: 'finance',
    inputs: [
      { key: 'fixedCosts', kind: 'number', min: 0, placeholder: 40000 },
      { key: 'price', kind: 'number', min: 0, placeholder: 90 },
      { key: 'variableCost', kind: 'number', min: 0, placeholder: 55 },
    ],
    outputs: [
      { key: 'breakEvenUnits', format: 'integer', primary: true },
      { key: 'breakEvenRevenue', format: 'currency' },
      { key: 'contributionPerUnit', format: 'currency' },
    ],
    compute: ({ fixedCosts, price, variableCost }) => {
      const F = n(fixedCosts), P = n(price), V = n(variableCost)
      if (F === undefined || P === undefined || V === undefined) {
        return { breakEvenUnits: null, breakEvenRevenue: null, contributionPerUnit: null }
      }
      const contribution = P - V
      if (contribution <= 0) {
        return { breakEvenUnits: null, breakEvenRevenue: null, contributionPerUnit: round(contribution) }
      }
      const units = Math.ceil(F / contribution)
      return {
        contributionPerUnit: round(contribution),
        breakEvenUnits: units,
        breakEvenRevenue: round(units * P),
      }
    },
    faqs: 4,
  },
  {
    // Compound growth with recurring contributions, then deflated to
    // today's money and charged a fee. Contributions are END of period
    // (ordinary annuity) — the conservative convention, and the one that
    // matches a standing order paid at month end.
    id: 'investment-simulator',
    slugs: { en: 'investment-simulator', it: 'simulatore-investimenti' },
    category: 'finance',
    inputs: [
      { key: 'initial', kind: 'number', min: 0, placeholder: 10000 },
      { key: 'monthly', kind: 'number', min: 0, placeholder: 300 },
      { key: 'years', kind: 'integer', min: 1, placeholder: 15 },
      { key: 'returnRate', kind: 'percent', placeholder: 6 },
      { key: 'inflation', kind: 'percent', optional: true, placeholder: 2 },
      { key: 'fees', kind: 'percent', optional: true, placeholder: 0.5 },
    ],
    outputs: [
      { key: 'finalValue', format: 'currency', primary: true },
      { key: 'realValue', format: 'currency' },
      { key: 'contributed', format: 'currency' },
      { key: 'growth', format: 'currency' },
    ],
    compute: ({ initial, monthly, years, returnRate, inflation, fees }) => {
      const P = n(initial), M = n(monthly), Y = n(years), R = n(returnRate)
      if (P === undefined || M === undefined || Y === undefined || R === undefined || Y < 1) {
        return { finalValue: null, realValue: null, contributed: null, growth: null }
      }
      const annualNet = R / 100 - (n(fees) ?? 0) / 100
      const monthlyRate = (1 + annualNet) ** (1 / 12) - 1
      const months = Math.floor(Y) * 12
      let value = P
      for (let m = 0; m < months; m++) value = value * (1 + monthlyRate) + M
      const contributed = P + M * months
      const infl = (n(inflation) ?? 0) / 100
      return {
        finalValue: round(value),
        realValue: round(value / (1 + infl) ** Math.floor(Y)),
        contributed: round(contributed),
        growth: round(value - contributed),
      }
    },
    faqs: 4,
  },
  {
    // Net invested capital = operating assets − operating liabilities.
    // Cash is EXCLUDED from operating assets by definition; the field
    // exists so a reader who included it can have it taken back out,
    // which is the mistake this calculation invites.
    id: 'net-invested-capital',
    slugs: { en: 'net-invested-capital-calculator', it: 'capitale-investito-netto' },
    category: 'finance',
    inputs: [
      { key: 'fixedAssets', kind: 'number', min: 0, placeholder: 400000 },
      { key: 'operatingAssets', kind: 'number', min: 0, placeholder: 250000 },
      { key: 'operatingLiabilities', kind: 'number', min: 0, placeholder: 120000 },
      { key: 'cash', kind: 'number', min: 0, optional: true, placeholder: 60000 },
    ],
    outputs: [
      { key: 'nic', format: 'currency', primary: true },
      { key: 'workingCapital', format: 'currency' },
    ],
    compute: ({ fixedAssets, operatingAssets, operatingLiabilities, cash }) => {
      const F = n(fixedAssets), A = n(operatingAssets), L = n(operatingLiabilities)
      if (F === undefined || A === undefined || L === undefined) return { nic: null, workingCapital: null }
      const wc = A - (n(cash) ?? 0) - L
      return { workingCapital: round(wc), nic: round(F + wc) }
    },
    faqs: 3,
  },
  {
    // Reverse factoring: what the buyer's supplier pays to be paid early,
    // and what the buyer gains in working capital by extending terms.
    // Discount = invoice × rate × days/365 (actual/365, the money-market
    // convention these facilities are quoted on).
    id: 'reverse-factoring',
    slugs: { en: 'reverse-factoring-calculator', it: 'reverse-factoring' },
    category: 'finance',
    inputs: [
      { key: 'invoiceValue', kind: 'number', min: 0, placeholder: 500000 },
      { key: 'extensionDays', kind: 'integer', min: 0, placeholder: 60 },
      { key: 'discountRate', kind: 'percent', min: 0, placeholder: 4.5 },
    ],
    outputs: [
      { key: 'financingCost', format: 'currency', primary: true },
      { key: 'netToSupplier', format: 'currency' },
      { key: 'effectiveAnnualRate', format: 'percent' },
    ],
    compute: ({ invoiceValue, extensionDays, discountRate }) => {
      const V = n(invoiceValue), D = n(extensionDays), R = n(discountRate)
      if (V === undefined || D === undefined || R === undefined) {
        return { financingCost: null, netToSupplier: null, effectiveAnnualRate: null }
      }
      const cost = V * (R / 100) * (D / 365)
      return {
        financingCost: round(cost),
        netToSupplier: round(V - cost),
        effectiveAnnualRate: D > 0 && V - cost !== 0 ? pct((cost / (V - cost)) * (365 / D)) : null,
      }
    },
    faqs: 3,
  },

  /* ──────────────────────── inventory ──────────────────────── */
  {
    // ROP = average daily demand × lead time + safety stock.
    // Both old slugs are the SAME calculator; they become one tool.
    id: 'reorder-point',
    slugs: { en: 'reorder-point-calculator', it: 'punto-di-riordino' },
    category: 'inventory',
    inputs: [
      { key: 'dailyDemand', kind: 'number', min: 0, placeholder: 40 },
      { key: 'leadTime', kind: 'number', min: 0, placeholder: 7 },
      { key: 'safetyStock', kind: 'number', min: 0, optional: true, placeholder: 60 },
    ],
    outputs: [
      { key: 'reorderPoint', format: 'integer', primary: true },
      { key: 'leadTimeDemand', format: 'integer' },
    ],
    compute: ({ dailyDemand, leadTime, safetyStock }) => {
      const D = n(dailyDemand), L = n(leadTime)
      if (D === undefined || L === undefined) return { reorderPoint: null, leadTimeDemand: null }
      const ltd = D * L
      return { leadTimeDemand: Math.ceil(ltd), reorderPoint: Math.ceil(ltd + (n(safetyStock) ?? 0)) }
    },
    faqs: 4,
  },
  {
    // Inventory turnover = COGS / average inventory; days = 365 / turns.
    id: 'inventory-turnover',
    slugs: { en: 'inventory-turnover-calculator', it: 'rotazione-scorte' },
    category: 'inventory',
    inputs: [
      { key: 'cogs', kind: 'number', min: 0, placeholder: 900000 },
      { key: 'averageInventory', kind: 'number', min: 0, placeholder: 150000 },
    ],
    outputs: [
      { key: 'turnover', format: 'number', primary: true },
      { key: 'daysOfInventory', format: 'days' },
    ],
    compute: ({ cogs, averageInventory }) => {
      const t = div(cogs, averageInventory)
      return { turnover: round(t), daysOfInventory: t !== null && t !== 0 ? round(365 / t, 1) : null }
    },
    faqs: 3,
  },
  {
    // DIO = average inventory / COGS × days in period.
    id: 'days-inventory',
    slugs: { en: 'days-inventory-on-hand', it: 'giorni-di-giacenza-magazzino' },
    category: 'inventory',
    inputs: [
      { key: 'averageInventory', kind: 'number', min: 0, placeholder: 150000 },
      { key: 'cogs', kind: 'number', min: 0, placeholder: 900000 },
      { key: 'periodDays', kind: 'integer', min: 1, placeholder: 365 },
    ],
    outputs: [
      { key: 'dio', format: 'days', primary: true },
      { key: 'turnover', format: 'number' },
    ],
    compute: ({ averageInventory, cogs, periodDays }) => {
      const ratio = div(averageInventory, cogs)
      const P = n(periodDays)
      if (ratio === null || P === undefined) return { dio: null, turnover: null }
      return { dio: round(ratio * P, 1), turnover: round(div(cogs, averageInventory)) }
    },
    faqs: 3,
  },
  {
    // Sell-through = units sold / units received. Over 100% is real
    // (returns, backorders) so it is not clamped — it is flagged in copy.
    id: 'sell-through',
    slugs: { en: 'sell-through-rate-calculator', it: 'tasso-di-vendita-sell-through' },
    category: 'inventory',
    inputs: [
      { key: 'unitsReceived', kind: 'integer', min: 0, placeholder: 500 },
      { key: 'unitsSold', kind: 'integer', min: 0, placeholder: 340 },
    ],
    outputs: [
      { key: 'sellThrough', format: 'percent', primary: true },
      { key: 'unitsRemaining', format: 'integer' },
    ],
    compute: ({ unitsReceived, unitsSold }) => {
      const R = n(unitsReceived), S = n(unitsSold)
      if (R === undefined || S === undefined) return { sellThrough: null, unitsRemaining: null }
      return { sellThrough: pct(div(S, R)), unitsRemaining: round(R - S) }
    },
    faqs: 3,
  },

  /* ────────────────────────── sales ────────────────────────── */
  {
    // AOV = revenue / orders.
    id: 'aov',
    slugs: { en: 'aov-calculator', it: 'calcolo-valore-medio-ordine' },
    category: 'sales',
    inputs: [
      { key: 'revenue', kind: 'number', min: 0, placeholder: 84000 },
      { key: 'orders', kind: 'integer', min: 0, placeholder: 1200 },
    ],
    outputs: [{ key: 'aov', format: 'currency', primary: true }],
    compute: ({ revenue, orders }) => ({ aov: round(div(revenue, orders)) }),
    faqs: 3,
  },
  {
    // Conversion = conversions / total. Revenue per lead rides along
    // because it is the number that makes the rate actionable.
    id: 'conversion-rate',
    slugs: { en: 'sales-conversion-calculator', it: 'calcolo-tasso-di-conversione' },
    category: 'sales',
    inputs: [
      { key: 'conversions', kind: 'integer', min: 0, placeholder: 84 },
      { key: 'total', kind: 'integer', min: 0, placeholder: 2400 },
      { key: 'revenue', kind: 'number', min: 0, optional: true, placeholder: 42000 },
    ],
    outputs: [
      { key: 'conversionRate', format: 'percent', primary: true },
      { key: 'revenuePerLead', format: 'currency' },
      { key: 'valuePerConversion', format: 'currency' },
    ],
    compute: ({ conversions, total, revenue }) => ({
      conversionRate: pct(div(conversions, total)),
      revenuePerLead: n(revenue) === undefined ? null : round(div(revenue, total)),
      valuePerConversion: n(revenue) === undefined ? null : round(div(revenue, conversions)),
    }),
    faqs: 4,
  },
  {
    // CLV = AOV × purchase frequency × lifespan. The simple
    // (non-discounted, non-margin) form, which is what the field labels
    // describe; the margin variant is named in the copy.
    id: 'customer-lifetime-value',
    slugs: { en: 'customer-lifetime-value-calculator', it: 'calcolo-valore-cliente-lifetime' },
    category: 'sales',
    inputs: [
      { key: 'averageOrderValue', kind: 'number', min: 0, placeholder: 70 },
      { key: 'purchasesPerYear', kind: 'number', min: 0, placeholder: 4 },
      { key: 'yearsRetained', kind: 'number', min: 0, placeholder: 3 },
      { key: 'grossMargin', kind: 'percent', min: 0, optional: true, placeholder: 60 },
    ],
    outputs: [
      { key: 'clv', format: 'currency', primary: true },
      { key: 'annualValue', format: 'currency' },
      { key: 'marginClv', format: 'currency' },
    ],
    compute: ({ averageOrderValue, purchasesPerYear, yearsRetained, grossMargin }) => {
      const A = n(averageOrderValue), F = n(purchasesPerYear), Y = n(yearsRetained)
      if (A === undefined || F === undefined || Y === undefined) {
        return { clv: null, annualValue: null, marginClv: null }
      }
      const clv = A * F * Y
      const m = n(grossMargin)
      return {
        annualValue: round(A * F),
        clv: round(clv),
        marginClv: m === undefined ? null : round(clv * (m / 100)),
      }
    },
    faqs: 4,
  },
  {
    // Churn = customers lost / customers at start.
    // Losses are DERIVED (start + acquired − end) rather than asked for,
    // because the two are inconsistent surprisingly often and a derived
    // number cannot contradict the others on the same screen.
    id: 'churn-rate',
    slugs: { en: 'churn-rate-calculator', it: 'calcolo-tasso-di-abbandono' },
    category: 'sales',
    inputs: [
      { key: 'customersStart', kind: 'integer', min: 0, placeholder: 1000 },
      { key: 'customersEnd', kind: 'integer', min: 0, placeholder: 960 },
      { key: 'customersAcquired', kind: 'integer', min: 0, optional: true, placeholder: 120 },
    ],
    outputs: [
      { key: 'churnRate', format: 'percent', primary: true },
      { key: 'churnedCustomers', format: 'integer' },
      { key: 'retentionRate', format: 'percent' },
    ],
    compute: ({ customersStart, customersEnd, customersAcquired }) => {
      const S = n(customersStart), E = n(customersEnd)
      if (S === undefined || E === undefined) {
        return { churnRate: null, churnedCustomers: null, retentionRate: null }
      }
      const lost = S + (n(customersAcquired) ?? 0) - E
      const rate = div(lost, S)
      return {
        churnedCustomers: round(lost, 0),
        churnRate: pct(rate),
        retentionRate: rate === null ? null : pct(1 - rate),
      }
    },
    faqs: 4,
  },
  {
    // Final price after a percentage discount, and the saving.
    id: 'percentage-discount',
    slugs: { en: 'percentage-discount-calculator', it: 'sconto-percentuale' },
    category: 'sales',
    inputs: [
      { key: 'originalPrice', kind: 'number', min: 0, placeholder: 249 },
      { key: 'discountPercent', kind: 'percent', min: 0, placeholder: 20 },
    ],
    outputs: [
      { key: 'finalPrice', format: 'currency', primary: true },
      { key: 'saving', format: 'currency' },
    ],
    compute: ({ originalPrice, discountPercent }) => {
      const P = n(originalPrice), D = n(discountPercent)
      if (P === undefined || D === undefined) return { finalPrice: null, saving: null }
      const saving = P * (D / 100)
      return { saving: round(saving), finalPrice: round(P - saving) }
    },
    faqs: 3,
  },

  /* ──────────────────────── marketing ──────────────────────── */
  {
    // NPS = %promoters − %detractors, on a −100..+100 scale.
    // Passives count in the denominator and nowhere else, which is the
    // part people get wrong.
    id: 'nps',
    slugs: { en: 'nps-calculator', it: 'net-promoter-score' },
    category: 'marketing',
    inputs: [
      { key: 'promoters', kind: 'integer', min: 0, placeholder: 240 },
      { key: 'passives', kind: 'integer', min: 0, placeholder: 120 },
      { key: 'detractors', kind: 'integer', min: 0, placeholder: 40 },
    ],
    outputs: [
      { key: 'nps', format: 'number', primary: true },
      { key: 'promoterPct', format: 'percent' },
      { key: 'detractorPct', format: 'percent' },
      { key: 'responses', format: 'integer' },
    ],
    compute: ({ promoters, passives, detractors }) => {
      const P = n(promoters), N = n(passives), D = n(detractors)
      if (P === undefined || N === undefined || D === undefined) {
        return { nps: null, promoterPct: null, detractorPct: null, responses: null }
      }
      const total = P + N + D
      if (total === 0) return { nps: null, promoterPct: null, detractorPct: null, responses: 0 }
      return {
        responses: total,
        promoterPct: pct(P / total),
        detractorPct: pct(D / total),
        nps: round(((P - D) / total) * 100, 1),
      }
    },
    faqs: 4,
  },

  /* ──────────────────────── operations ─────────────────────── */
  {
    // Revenue per employee and per hour — the two productivity numbers a
    // small business can actually compute without a time-tracking system.
    id: 'employee-productivity',
    slugs: { en: 'employee-productivity-calculator', it: 'calcolo-produttivita-dipendente' },
    category: 'operations',
    inputs: [
      { key: 'output', kind: 'number', min: 0, placeholder: 800000 },
      { key: 'employees', kind: 'number', min: 0, placeholder: 12 },
      { key: 'hoursPerEmployee', kind: 'number', min: 0, optional: true, placeholder: 1600 },
      { key: 'labourCost', kind: 'number', min: 0, optional: true, placeholder: 420000 },
    ],
    outputs: [
      { key: 'perEmployee', format: 'currency', primary: true },
      { key: 'perHour', format: 'currency' },
      { key: 'labourRatio', format: 'number' },
    ],
    compute: ({ output, employees, hoursPerEmployee, labourCost }) => {
      const O = n(output), E = n(employees), H = n(hoursPerEmployee)
      return {
        perEmployee: round(div(O, E)),
        perHour: O !== undefined && E !== undefined && H !== undefined && E * H !== 0
          ? round(O / (E * H)) : null,
        labourRatio: n(labourCost) === undefined ? null : round(div(O, labourCost)),
      }
    },
    faqs: 3,
  },
  {
    // Renovation cost per square metre. A quote-shaped estimate: a base
    // rate per finish level, plus percentage uplifts for the systems
    // being touched. The rates are stated in the copy as Italian market
    // ranges rather than hidden — an estimate whose basis is invisible
    // is a number the reader cannot argue with or correct.
    id: 'renovation-cost',
    slugs: { en: 'renovation-cost-calculator', it: 'costo-al-mq-ristrutturazione' },
    category: 'operations',
    inputs: [
      { key: 'squareMetres', kind: 'number', min: 0, placeholder: 90 },
      { key: 'ratePerSqm', kind: 'number', min: 0, placeholder: 750 },
      { key: 'systemsUpliftPct', kind: 'percent', min: 0, optional: true, placeholder: 25 },
      { key: 'contingencyPct', kind: 'percent', min: 0, optional: true, placeholder: 10 },
    ],
    outputs: [
      { key: 'total', format: 'currency', primary: true },
      { key: 'baseCost', format: 'currency' },
      { key: 'effectivePerSqm', format: 'currency' },
    ],
    compute: ({ squareMetres, ratePerSqm, systemsUpliftPct, contingencyPct }) => {
      const S = n(squareMetres), R = n(ratePerSqm)
      if (S === undefined || R === undefined) return { total: null, baseCost: null, effectivePerSqm: null }
      const base = S * R
      const total = base * (1 + (n(systemsUpliftPct) ?? 0) / 100) * (1 + (n(contingencyPct) ?? 0) / 100)
      return { baseCost: round(base), total: round(total), effectivePerSqm: round(div(total, S)) }
    },
    faqs: 3,
  },
  {
    // Volumetric vs actual weight — the rule every carrier prices on and
    // almost no small shipper knows. Chargeable weight is the greater of
    // the two; the divisor is the carrier's (5000 for most European road
    // and express services, 6000 for some air).
    id: 'shipping-cost',
    slugs: { en: 'shipping-cost-calculator', it: 'calcola-costo-spedizione' },
    category: 'operations',
    inputs: [
      { key: 'lengthCm', kind: 'number', min: 0, placeholder: 40 },
      { key: 'widthCm', kind: 'number', min: 0, placeholder: 30 },
      { key: 'heightCm', kind: 'number', min: 0, placeholder: 20 },
      { key: 'actualWeightKg', kind: 'number', min: 0, placeholder: 3.5 },
      { key: 'ratePerKg', kind: 'number', min: 0, placeholder: 4.2 },
      { key: 'divisor', kind: 'integer', min: 1, optional: true, placeholder: 5000 },
    ],
    outputs: [
      { key: 'shippingCost', format: 'currency', primary: true },
      { key: 'chargeableWeight', format: 'number' },
      { key: 'volumetricWeight', format: 'number' },
    ],
    compute: ({ lengthCm, widthCm, heightCm, actualWeightKg, ratePerKg, divisor }) => {
      const L = n(lengthCm), W = n(widthCm), H = n(heightCm), A = n(actualWeightKg), R = n(ratePerKg)
      if (L === undefined || W === undefined || H === undefined || A === undefined) {
        return { shippingCost: null, chargeableWeight: null, volumetricWeight: null }
      }
      // An explicitly-supplied divisor of zero or less is not a
      // divisor. `?? 5000` only covers a BLANK field, so 0 fell straight
      // through into a division and produced NaN — found by the property
      // test rather than by anyone reading this line.
      const supplied = n(divisor)
      if (supplied !== undefined && supplied <= 0) {
        return { shippingCost: null, chargeableWeight: null, volumetricWeight: null }
      }
      const vol = (L * W * H) / (supplied ?? 5000)
      const chargeable = Math.max(vol, A)
      return {
        volumetricWeight: round(vol, 2),
        chargeableWeight: round(chargeable, 2),
        shippingCost: R === undefined ? null : round(chargeable * R),
      }
    },
    faqs: 4,
  },
  {
    // Cost-benefit: BCR = PV(benefits) / PV(costs), both discounted over
    // the horizon. A BCR of 1.0 is the decision boundary and the copy
    // says so — the number is meaningless without that anchor.
    id: 'cost-benefit',
    slugs: { en: 'cost-benefit-analysis-calculator', it: 'analisi-costi-benefici' },
    category: 'operations',
    inputs: [
      { key: 'upfrontCost', kind: 'number', min: 0, placeholder: 60000 },
      { key: 'annualCost', kind: 'number', min: 0, placeholder: 8000 },
      { key: 'annualBenefit', kind: 'number', min: 0, placeholder: 32000 },
      { key: 'years', kind: 'integer', min: 1, placeholder: 5 },
      { key: 'rate', kind: 'percent', optional: true, placeholder: 6 },
    ],
    outputs: [
      { key: 'bcr', format: 'number', primary: true },
      { key: 'netBenefit', format: 'currency' },
      { key: 'pvBenefits', format: 'currency' },
      { key: 'pvCosts', format: 'currency' },
    ],
    compute: ({ upfrontCost, annualCost, annualBenefit, years, rate }) => {
      const U = n(upfrontCost), AC = n(annualCost), AB = n(annualBenefit), Y = n(years)
      if (U === undefined || AC === undefined || AB === undefined || Y === undefined || Y < 1) {
        return { bcr: null, netBenefit: null, pvBenefits: null, pvCosts: null }
      }
      const r = (n(rate) ?? 0) / 100
      let pvB = 0, pvC = U
      for (let t = 1; t <= Math.floor(Y); t++) {
        pvB += AB / (1 + r) ** t
        pvC += AC / (1 + r) ** t
      }
      return {
        pvBenefits: round(pvB),
        pvCosts: round(pvC),
        netBenefit: round(pvB - pvC),
        bcr: round(div(pvB, pvC)),
      }
    },
    faqs: 4,
  },
  {
    // Profitability: gross and net margin plus ROA, from the four lines
    // every set of accounts has.
    id: 'profitability',
    slugs: { en: 'profitability-calculator', it: 'analisi-redditivita' },
    category: 'finance',
    inputs: [
      { key: 'revenue', kind: 'number', min: 0, placeholder: 1200000 },
      { key: 'cogs', kind: 'number', min: 0, placeholder: 720000 },
      { key: 'operatingExpenses', kind: 'number', min: 0, placeholder: 300000 },
      { key: 'totalAssets', kind: 'number', min: 0, optional: true, placeholder: 900000 },
    ],
    outputs: [
      { key: 'netMarginPct', format: 'percent', primary: true },
      { key: 'grossMarginPct', format: 'percent' },
      { key: 'operatingProfit', format: 'currency' },
      { key: 'roa', format: 'percent' },
    ],
    compute: ({ revenue, cogs, operatingExpenses, totalAssets }) => {
      const R = n(revenue), C = n(cogs), O = n(operatingExpenses)
      if (R === undefined || C === undefined || O === undefined) {
        return { netMarginPct: null, grossMarginPct: null, operatingProfit: null, roa: null }
      }
      const op = R - C - O
      return {
        grossMarginPct: pct(div(R - C, R)),
        operatingProfit: round(op),
        netMarginPct: pct(div(op, R)),
        roa: n(totalAssets) === undefined ? null : pct(div(op, totalAssets)),
      }
    },
    faqs: 3,
  },
  {
    // KPI attainment = actual / target, and the gap that closes it.
    // Works for lower-is-better targets too, which most KPI calculators
    // silently get backwards.
    id: 'kpi-attainment',
    slugs: { en: 'kpi-attainment-calculator', it: 'gestione-kpi' },
    category: 'operations',
    inputs: [
      { key: 'actual', kind: 'number', placeholder: 84 },
      { key: 'target', kind: 'number', placeholder: 100 },
      { key: 'baseline', kind: 'number', optional: true, placeholder: 60 },
    ],
    outputs: [
      { key: 'attainment', format: 'percent', primary: true },
      { key: 'gap', format: 'number' },
      { key: 'progressFromBaseline', format: 'percent' },
    ],
    compute: ({ actual, target, baseline }) => {
      const A = n(actual), T = n(target), B = n(baseline)
      if (A === undefined || T === undefined) return { attainment: null, gap: null, progressFromBaseline: null }
      return {
        attainment: pct(div(A, T)),
        gap: round(T - A),
        progressFromBaseline: B === undefined || T - B === 0 ? null : pct((A - B) / (T - B)),
      }
    },
    faqs: 3,
  },
  {
    // Holiday entitlement for hourly domestic workers under the Italian
    // CCNL: 26 working days a year, accrued monthly, pro-rated by hours
    // for part-time. Fractions of a month of 15 days or more count as a
    // full month, which is the rule and not a rounding choice.
    id: 'domestic-worker-holiday',
    slugs: { en: 'domestic-worker-holiday-calculator', it: 'ferie-per-colf-a-ore' },
    category: 'operations',
    inputs: [
      { key: 'hoursPerWeek', kind: 'number', min: 0, placeholder: 20 },
      { key: 'monthsWorked', kind: 'number', min: 0, placeholder: 12 },
      { key: 'fullTimeHours', kind: 'number', min: 1, optional: true, placeholder: 40 },
    ],
    outputs: [
      { key: 'holidayDays', format: 'number', primary: true },
      { key: 'holidayHours', format: 'number' },
      { key: 'accrualPerMonth', format: 'number' },
    ],
    compute: ({ hoursPerWeek, monthsWorked, fullTimeHours }) => {
      const H = n(hoursPerWeek), M = n(monthsWorked)
      if (H === undefined || M === undefined) {
        return { holidayDays: null, holidayHours: null, accrualPerMonth: null }
      }
      const full = n(fullTimeHours) ?? 40
      const partTime = full > 0 ? Math.min(H / full, 1) : 0
      const days = 26 * (Math.min(M, 12) / 12) * partTime
      return {
        accrualPerMonth: round((26 / 12) * partTime, 2),
        holidayDays: round(days, 1),
        holidayHours: round(days * (H / 6), 1),
      }
    },
    faqs: 4,
  },

  /* ─────────────────────────── data ────────────────────────── */
  {
    // Sample vs population variance — the n−1 against n that the two
    // buttons on the old tool never explained. Both are returned, always,
    // so the reader sees the difference rather than picking blind.
    id: 'variance',
    // The live slug is English and sits at the root today, so it stays
    // the ENGLISH slug — inventing `variance-calculator` alongside it
    // would have retired a ranking URL to a redirect for no gain. Caught
    // by the legacy-map test, which is the one that knows what exists.
    slugs: { en: 'variance-calculator-online', it: 'calcolo-varianza' },
    category: 'data',
    inputs: [],
    outputs: [
      { key: 'sampleVariance', format: 'number', primary: true },
      { key: 'populationVariance', format: 'number' },
      { key: 'mean', format: 'number' },
      { key: 'sampleStdDev', format: 'number' },
      { key: 'count', format: 'integer' },
    ],
    // Series tools take their numbers from a textarea, not fields, so
    // `compute` is driven by `series` rather than the input list. Kept in
    // the same shape so one component renders every tool.
    compute: (v) => {
      const raw = (v as { series?: number[] }).series
      const xs = Array.isArray(raw) ? raw.filter((x) => Number.isFinite(x)) : []
      if (xs.length === 0) {
        return { sampleVariance: null, populationVariance: null, mean: null, sampleStdDev: null, count: 0 }
      }
      const mean = xs.reduce((a, b) => a + b, 0) / xs.length
      const ss = xs.reduce((a, b) => a + (b - mean) ** 2, 0)
      const pop = ss / xs.length
      const sample = xs.length > 1 ? ss / (xs.length - 1) : null
      return {
        count: xs.length,
        mean: round(mean, 4),
        populationVariance: round(pop, 4),
        sampleVariance: round(sample, 4),
        sampleStdDev: sample === null ? null : round(Math.sqrt(sample), 4),
      }
    },
    faqs: 4,
  },
  {
    // CEE balance sheet → riclassificato finanziario. Not a judgement
    // call and not an LLM job: the schema is fixed, and what an owner
    // actually wants out of it is four margins the CEE layout does not
    // show. The old page took an upload and called itself a generator;
    // the arithmetic underneath is this.
    id: 'balance-sheet-reclassification',
    slugs: {
      en: 'reclassified-balance-sheet',
      it: 'stato-patrimoniale-riclassificato-schema',
    },
    category: 'finance',
    inputs: [
      { key: 'fixedAssets', kind: 'number', min: 0, placeholder: 380000 },
      { key: 'inventory', kind: 'number', min: 0, placeholder: 90000 },
      { key: 'receivables', kind: 'number', min: 0, placeholder: 140000 },
      { key: 'cash', kind: 'number', min: 0, placeholder: 45000 },
      { key: 'equity', kind: 'number', placeholder: 300000 },
      { key: 'shortTermDebt', kind: 'number', min: 0, placeholder: 210000 },
      { key: 'longTermDebt', kind: 'number', min: 0, placeholder: 145000 },
    ],
    outputs: [
      { key: 'workingCapital', format: 'currency', primary: true },
      { key: 'treasuryMargin', format: 'currency' },
      { key: 'structuralMargin', format: 'currency' },
      { key: 'currentRatio', format: 'number' },
      { key: 'currentAssets', format: 'currency' },
      { key: 'debtToEquity', format: 'number' },
    ],
    compute: ({ fixedAssets, inventory, receivables, cash, equity, shortTermDebt, longTermDebt }) => {
      const F = n(fixedAssets), I = n(inventory), R = n(receivables), C = n(cash)
      const E = n(equity), S = n(shortTermDebt), L = n(longTermDebt)
      if ([F, I, R, C, E, S, L].some((x) => x === undefined)) {
        return {
          workingCapital: null, treasuryMargin: null, structuralMargin: null,
          currentRatio: null, currentAssets: null, debtToEquity: null,
        }
      }
      const currentAssets = (I as number) + (R as number) + (C as number)
      // Treasury margin excludes inventory deliberately: it asks whether
      // short-term debt could be met WITHOUT selling stock, which is the
      // question the working-capital figure quietly answers "yes" to.
      const liquid = (R as number) + (C as number)
      return {
        currentAssets: round(currentAssets),
        workingCapital: round(currentAssets - (S as number)),
        treasuryMargin: round(liquid - (S as number)),
        structuralMargin: round((E as number) - (F as number)),
        currentRatio: round(div(currentAssets, S)),
        debtToEquity: round(div((S as number) + (L as number), E)),
      }
    },
    faqs: 4,
  },
  {
    // Affitto d'azienda — the annual rent for leasing a going concern.
    //
    // Two anchors, because either alone misleads. The YIELD anchor prices
    // the rent as a return on the capital handed over; the EBITDA anchor
    // asks what share of the earnings that rent consumes. A rent that
    // looks fair as a yield and eats 80% of EBITDA is a business the
    // tenant cannot run, and that is the number a first-time lessee
    // never computes.
    id: 'business-lease',
    slugs: { en: 'business-lease-calculator', it: 'affitto-di-azienda' },
    category: 'finance',
    inputs: [
      { key: 'assetValue', kind: 'number', min: 0, placeholder: 450000 },
      { key: 'revenue', kind: 'number', min: 0, placeholder: 620000 },
      { key: 'operatingCosts', kind: 'number', min: 0, placeholder: 540000 },
      { key: 'yieldPct', kind: 'percent', min: 0, placeholder: 7 },
    ],
    outputs: [
      { key: 'annualRent', format: 'currency', primary: true },
      { key: 'monthlyRent', format: 'currency' },
      { key: 'ebitda', format: 'currency' },
      { key: 'rentToEbitda', format: 'percent' },
      { key: 'residualToTenant', format: 'currency' },
    ],
    compute: ({ assetValue, revenue, operatingCosts, yieldPct }) => {
      const A = n(assetValue), R = n(revenue), C = n(operatingCosts), Y = n(yieldPct)
      if (A === undefined || R === undefined || C === undefined || Y === undefined) {
        return {
          annualRent: null, monthlyRent: null, ebitda: null,
          rentToEbitda: null, residualToTenant: null,
        }
      }
      const ebitda = R - C
      const annualRent = A * (Y / 100)
      return {
        ebitda: round(ebitda),
        annualRent: round(annualRent),
        monthlyRent: round(annualRent / 12),
        // Null rather than a negative ratio when there are no earnings:
        // "the rent is −140% of EBITDA" is not a sentence that helps.
        rentToEbitda: ebitda > 0 ? pct(annualRent / ebitda) : null,
        residualToTenant: round(ebitda - annualRent),
      }
    },
    faqs: 4,
  },
  {
    // Sales forecast — Holt's linear trend (double exponential
    // smoothing), which is what "AI sales forecasting" is when you open
    // it up. Deterministic, sixty lines, and testable against a series
    // whose answer you can work out on paper.
    //
    // NOT Holt-Winters: seasonality needs at least two full cycles of
    // history to fit, and a tool that silently fits a season to eight
    // months of data produces confident nonsense. The copy says to use
    // the same month last year for seasonal businesses.
    id: 'sales-forecast',
    slugs: { en: 'sales-forecast-calculator', it: 'previsione-vendite' },
    category: 'sales',
    series: true,
    inputs: [
      { key: 'periodsAhead', kind: 'integer', min: 1, placeholder: 3 },
      { key: 'alpha', kind: 'number', min: 0, optional: true, placeholder: 0.3 },
      { key: 'beta', kind: 'number', min: 0, optional: true, placeholder: 0.1 },
    ],
    outputs: [
      { key: 'next', format: 'number', primary: true },
      { key: 'total', format: 'number' },
      { key: 'trend', format: 'number' },
      { key: 'level', format: 'number' },
      { key: 'periods', format: 'integer' },
    ],
    compute: (v) => {
      const xs = (v as { series?: number[] }).series ?? []
      const ahead = Math.floor(n(v.periodsAhead) ?? 0)
      const empty = { next: null, total: null, trend: null, level: null, periods: xs.length }
      // Two points is the minimum that defines a trend at all.
      if (xs.length < 2 || ahead < 1) return empty

      // Clamped to (0,1]: a smoothing constant outside that range is not
      // a slower forecast, it is a divergent one.
      const clamp = (x: number | undefined, fallback: number): number =>
        x === undefined || !(x > 0) || x > 1 ? fallback : x
      const alpha = clamp(n(v.alpha), 0.3)
      const beta = clamp(n(v.beta), 0.1)

      let level = xs[0]
      let trend = xs[1] - xs[0]
      for (let i = 1; i < xs.length; i++) {
        const prevLevel = level
        level = alpha * xs[i] + (1 - alpha) * (level + trend)
        trend = beta * (level - prevLevel) + (1 - beta) * trend
      }
      let total = 0
      for (let h = 1; h <= ahead; h++) total += level + h * trend
      return {
        periods: xs.length,
        level: round(level, 2),
        trend: round(trend, 2),
        next: round(level + trend, 2),
        total: round(total, 2),
      }
    },
    faqs: 4,
  },
  {
    // Distribution of a pasted series. The bin count defaults to Sturges
    // and stays editable: bin width changes what a histogram appears to
    // say, and a tool that picks silently is hiding its most
    // consequential knob.
    id: 'istogramma',
    slugs: { en: 'histogram-generator', it: 'istogramma-con-excel' },
    category: 'data',
    custom: 'histogram',
    extraKeys: ['seriesLabel', 'seriesPlaceholder', 'binsHint', 'caption'],
    inputs: [{ key: 'bins', kind: 'integer', min: 1, optional: true, placeholder: 8 }],
    outputs: [{ key: 'count', format: 'integer', primary: true }],
    faqs: 3,
  },
  {
    // Merge CSVs by header name, in the browser. The files never leave
    // the machine — no request is made at all.
    id: 'unire-csv',
    slugs: { en: 'merge-csv-files', it: 'unire-file-csv' },
    category: 'data',
    custom: 'csv-merge',
    extraKeys: [
      'filesHint', 'rowCount', 'remove', 'download', 'columnsFound', 'tooLarge', 'noHeaders',
    ],
    inputs: [{ key: 'files', kind: 'integer', optional: true, placeholder: 2 }],
    outputs: [{ key: 'rows', format: 'integer', primary: true }],
    faqs: 4,
  },
  {
    // Paste a table, get a chart. One axis, five series maximum — the
    // length of the validated palette.
    id: 'data-viz',
    slugs: { en: 'chart-maker', it: 'data-visualization-free' },
    category: 'data',
    custom: 'data-viz',
    extraKeys: [
      'dataPlaceholder', 'dataHint', 'seriesHint', 'caption', 'noNumeric',
      'kinds.bar', 'kinds.line',
    ],
    inputs: [
      { key: 'data', kind: 'integer', optional: true, placeholder: 1 },
      { key: 'kind', kind: 'integer', optional: true, placeholder: 1 },
      { key: 'series', kind: 'integer', optional: true, placeholder: 1 },
    ],
    outputs: [{ key: 'rows', format: 'integer', primary: true }],
    faqs: 3,
  },
  /* ── model-backed (custom: 'llm') ───────────────────────────────
   *
   * The nine that genuinely need a model. Their fields, prompts and
   * section lists live in `lib/tools/llm/specs.ts`, not here — this
   * registry owns what every tool has in common (slug, category, copy
   * keys, CMS override) and nothing else. `inputs` and `outputs` are
   * EMPTY for all nine on purpose: they take prose and return prose, so
   * there is no numeric field to declare and no figure to format, and
   * `extraKeys` carries their copy instead.
   */
  {
    id: 'financial-analysis',
    slugs: { en: 'financial-analysis', it: 'calcolatore-finanziario' },
    category: 'finance',
    custom: 'llm',
    extraKeys: [
      'inputs.situation', 'inputs.question', 'inputs.sector',
      'sections.reading', 'sections.drivers', 'sections.watch', 'sections.missing',
      'placeholder',
    ],
    inputs: [],
    outputs: [],
    faqs: 3,
  },
  {
    id: 'sales-analysis',
    slugs: { en: 'sales-data-analysis', it: 'analisi-vendite' },
    category: 'sales',
    custom: 'llm',
    extraKeys: [
      'inputs.table', 'inputs.context',
      'sections.shape', 'sections.patterns', 'sections.questions', 'sections.missing',
      'placeholder',
    ],
    inputs: [],
    outputs: [],
    faqs: 3,
  },
  {
    id: 'cost-analysis',
    slugs: { en: 'cost-analysis', it: 'analisi-costi' },
    category: 'finance',
    custom: 'llm',
    extraKeys: [
      'inputs.table', 'inputs.context',
      'sections.shape', 'sections.concentration', 'sections.levers', 'sections.missing',
      'placeholder',
    ],
    inputs: [],
    outputs: [],
    faqs: 3,
  },
  {
    id: 'risk-assessment',
    slugs: { en: 'business-risk-assessment', it: 'valutazione-rischio' },
    category: 'operations',
    custom: 'llm',
    extraKeys: [
      'inputs.situation', 'inputs.table', 'inputs.horizon',
      'options.quarter', 'options.year', 'options.three-years',
      'sections.exposures', 'sections.severity', 'sections.mitigations', 'sections.limits',
      'placeholder',
    ],
    inputs: [],
    outputs: [],
    faqs: 3,
  },
  {
    id: 'company-profile',
    slugs: { en: 'company-profile-generator', it: 'company-profile-esempio' },
    category: 'marketing',
    custom: 'llm',
    extraKeys: [
      'inputs.company', 'inputs.sector', 'inputs.audience', 'inputs.tone', 'inputs.facts',
      'options.plain', 'options.formal', 'options.warm',
      'sections.short', 'sections.long', 'sections.bullets', 'sections.missing',
      'placeholder',
    ],
    inputs: [],
    outputs: [],
    faqs: 3,
  },
  {
    id: 'communication-plan',
    slugs: { en: 'communication-plan-generator', it: 'piano-di-comunicazione' },
    category: 'marketing',
    custom: 'llm',
    extraKeys: [
      'inputs.goal', 'inputs.audience', 'inputs.channels', 'inputs.horizon',
      'options.quarter', 'options.year',
      'sections.objective', 'sections.audiences', 'sections.messages',
      'sections.calendar', 'sections.measure',
      'placeholder',
    ],
    inputs: [],
    outputs: [],
    faqs: 3,
  },
  {
    id: 'buyer-persona',
    slugs: { en: 'buyer-persona-generator', it: 'profilazione-clienti' },
    category: 'marketing',
    custom: 'llm',
    extraKeys: [
      'inputs.product', 'inputs.market', 'inputs.segment',
      'sections.persona', 'sections.jobs', 'sections.objections', 'sections.channels',
      'placeholder',
    ],
    inputs: [],
    outputs: [],
    faqs: 3,
  },
  {
    id: 'conflict-analysis',
    slugs: { en: 'conflict-management-advisor', it: 'gestione-dei-conflitti' },
    category: 'operations',
    custom: 'llm',
    extraKeys: [
      'inputs.situation', 'inputs.role', 'inputs.outcome',
      'options.manager', 'options.peer', 'options.report', 'options.external',
      'sections.reading', 'sections.interests', 'sections.moves', 'sections.caution',
      'placeholder',
    ],
    inputs: [],
    outputs: [],
    faqs: 3,
  },
  {
    id: 'communication-review',
    slugs: { en: 'communication-review', it: 'competenza-relazionale' },
    category: 'operations',
    custom: 'llm',
    extraKeys: [
      'inputs.sample', 'inputs.context', 'inputs.goal',
      'options.clarity', 'options.persuasion', 'options.de-escalation',
      'sections.reading', 'sections.strengths', 'sections.risks', 'sections.rewrite',
      'placeholder',
    ],
    inputs: [],
    outputs: [],
    faqs: 3,
  },
]

/** Tools that take a pasted number series. */
/**
 * Every tool, with its per-locale slugs resolved.
 *
 * Merged rather than mutated: `slugs.generated.ts` is data, this is the one
 * place the two are joined, and no consumer has to know the split exists —
 * `tool.slugs` is complete for all 21 locales by the time anyone reads it.
 * The authored `en`/`it` values win, so a hand-written slug can never be
 * overwritten by a regenerated one.
 */
export const TOOLS: ToolDef[] = AUTHORED_TOOLS.map((tool) => ({
  ...tool,
  slugs: { ...(LOCALE_SLUGS[tool.id] ?? {}), ...tool.slugs },
}))

export const SERIES_TOOLS: readonly string[] = TOOLS.filter((t) => t.series).map((t) => t.id)

/** Every slug, in every locale, mapped to its tool. */
export function slugIndex(): Map<string, { tool: ToolDef; locale: string }> {
  const index = new Map<string, { tool: ToolDef; locale: string }>()
  for (const tool of TOOLS) {
    for (const [locale, slug] of Object.entries(tool.slugs)) {
      index.set(`${locale}:${slug}`, { tool, locale })
    }
  }
  return index
}

/**
 * A route param as the app compares it: DECODED.
 *
 * Next hands `[slug]` to the page percent-ENCODED, and the registry stores
 * every slug decoded (`src/fields/slug.ts`'s rule; slugs.test.ts pins the
 * round trip). Until 2026-09-23 the tools page compared the two raw, so
 * `roi計算ツール` arrived as `roi%E8%A8%88…`, matched nothing, and every
 * tool page in the eight non-Latin locales — zh, tc, ar, uk, th, he, ko,
 * ja, 328 pages — was a 404 under an index that linked to it. Every other
 * dynamic route in the app already decodes (the main site's
 * `[...segments]`, help, the quarterly issues); this is the same rule in
 * one place. A malformed escape is not a slug: it falls through as-is and
 * matches nothing, so the page 404s it like any unknown slug.
 */
export function decodeSlug(raw: string): string {
  try {
    return decodeURIComponent(raw)
  } catch {
    return raw
  }
}

/** The tool a slug names in a locale, falling back to the English slug. */
export function toolBySlug(locale: string, slug: string): ToolDef | undefined {
  return (
    TOOLS.find((t) => t.slugs[locale] === slug) ??
    TOOLS.find((t) => t.slugs.en === slug)
  )
}

/** A tool's slug in a locale — its English slug where it has no own. */
export const slugFor = (tool: ToolDef, locale: string): string => tool.slugs[locale] ?? tool.slugs.en

/**
 * Look a tool up by id.
 *
 * This exists so the CLIENT can do the lookup. A `ToolDef` carries
 * `compute`, a function, and React cannot serialise a function across
 * the server/client boundary — passing the whole object into
 * `<Calculator>` fails the production build with "Functions cannot be
 * passed directly to Client Components", though `next dev` renders it
 * happily. The server passes the id; the client resolves it here.
 */
export function toolById(id: string): ToolDef | undefined {
  return TOOLS.find((t) => t.id === id)
}

export const CATEGORIES = ['finance', 'inventory', 'sales', 'marketing', 'operations', 'data'] as const
