// Generated by electe-web/scripts/export-tools-repo.ts from electe-migration@8e52bf6 on 2026-09-29. Do not edit here: change the source and re-export.
// Source: electe-web/src/lib/tools/slugs.test.ts
import { describe, expect, it } from 'vitest'

import { localeCodes } from './locales'

import { TOOLS, decodeSlug, slugFor, toolBySlug } from './registry'
import { LOCALE_SLUGS } from './slugs.generated'

/**
 * A SLUG IS A PERMANENT URL, which is the only reason this file is as
 * strict as it is.
 *
 * Copy can be rewritten and redeployed; a slug that ships and then moves
 * costs a redirect, a re-crawl and whatever ranking the old address had.
 * So these assertions are about the things that cannot be undone: that
 * every locale has one, that no two tools collide inside a locale, that
 * the string survives a URL round-trip, and that `en` and `it` — the two
 * with indexed URLs on the live property — are exactly what
 * `lib/tools/legacy.ts` maps the old addresses onto.
 */
describe('tool slugs', () => {
  it('gives every tool a slug in all 21 locales', () => {
    const gaps: string[] = []
    for (const tool of TOOLS) {
      for (const locale of localeCodes) {
        if (typeof tool.slugs[locale] !== 'string' || tool.slugs[locale] === '') {
          gaps.push(`${locale}:${tool.id}`)
        }
      }
    }
    expect(gaps, `tools with no slug: ${gaps.slice(0, 10).join(', ')}`).toEqual([])
  })

  it('has no duplicate slug inside a locale', () => {
    // Two tools sharing a slug is a route that serves whichever the
    // finder reaches first — silently, and differently per locale.
    const clashes: string[] = []
    for (const locale of localeCodes) {
      const seen = new Map<string, string>()
      for (const tool of TOOLS) {
        const slug = slugFor(tool, locale)
        const other = seen.get(slug)
        if (other) clashes.push(`${locale}: ${other} and ${tool.id} both "${slug}"`)
        seen.set(slug, tool.id)
      }
    }
    expect(clashes).toEqual([])
  })

  it('survives a percent-encoding round trip and carries no reserved character', () => {
    // Non-Latin slugs are stored DECODED (src/fields/slug.ts) and encoded at
    // the router/sitemap/hreflang layer, so the decoded form has to be
    // exactly recoverable. A stray `/`, `?` or `#` would not be a slug at
    // all — it would be a second path segment or a query string.
    const bad: string[] = []
    for (const tool of TOOLS) {
      for (const locale of localeCodes) {
        const slug = slugFor(tool, locale)
        if (decodeURIComponent(encodeURIComponent(slug)) !== slug) bad.push(`${locale}:${tool.id} round-trip`)
        if (/[/?#[\]@!$&'()*+,;=%\s]/.test(slug)) bad.push(`${locale}:${tool.id} reserved char`)
      }
    }
    expect(bad, bad.slice(0, 8).join(', ')).toEqual([])
  })

  it('resolves every slug in the percent-ENCODED form the route param arrives in', () => {
    // Next hands `[slug]` to the page encoded. Found live on 2026-09-23:
    // the eight non-Latin locales had a translated index whose 41 links
    // each led to a 404, because the page compared the raw param against
    // the decoded registry slug. This is the route's input, end to end.
    const bad: string[] = []
    for (const tool of TOOLS) {
      for (const locale of localeCodes) {
        const arrives = encodeURIComponent(slugFor(tool, locale))
        if (toolBySlug(locale, decodeSlug(arrives))?.id !== tool.id) bad.push(`${locale}:${tool.id}`)
      }
    }
    expect(bad, bad.slice(0, 8).join(', ')).toEqual([])
    // A malformed escape is not a slug and must not throw.
    expect(decodeSlug('%E3%81')).toBe('%E3%81')
    expect(toolBySlug('ja', decodeSlug('%E3%81'))).toBeUndefined()
  })

  it('stores every slug NFC-normalised', () => {
    // The live crawl caught Weglot storing Korean as DECOMPOSED jamo
    // (%E1%84%80%E1%85%A1…). That is a different byte string from the
    // composed form a browser or the CMS produces, so the two spellings of
    // the same slug never match each other.
    const bad = TOOLS.flatMap((tool) =>
      localeCodes
        .filter((locale) => slugFor(tool, locale) !== slugFor(tool, locale).normalize('NFC'))
        .map((locale) => `${locale}:${tool.id}`),
    )
    expect(bad).toEqual([])
  })

  it('keeps the en and it slugs the legacy map depends on', () => {
    // These are live, indexed URLs. lib/tools/legacy.ts maps the old
    // addresses onto them, and legacy.test.ts checks that mapping — but
    // nothing there would notice a slug being regenerated out from under it.
    const t = (id: string) => TOOLS.find((x) => x.id === id)!
    expect(t('reorder-point').slugs.it).toBe('punto-di-riordino')
    expect(t('reorder-point').slugs.en).toBe('reorder-point-calculator')
    expect(t('percentage-discount').slugs.it).toBe('sconto-percentuale')
    // The live variance URL is ENGLISH and sits at the root, so it is the
    // `en` slug; Italian got its own. See the note in registry.ts.
    expect(t('variance').slugs.en).toBe('variance-calculator-online')
    expect(t('variance').slugs.it).toBe('calcolo-varianza')
    expect(t('unire-csv').slugs.it).toBe('unire-file-csv')
  })

  it('never lets a locale slug shadow a different tool English slug', () => {
    // toolBySlug tries the locale slug and then falls back to the English
    // one, so the old /tools/fr/roi-calculator addresses keep working. That
    // fallback breaks if some tool's French slug happens to equal ANOTHER
    // tool's English slug — the French page would shadow the English URL.
    const enBySlug = new Map(TOOLS.map((t) => [t.slugs.en, t.id]))
    const shadows: string[] = []
    for (const tool of TOOLS) {
      for (const locale of localeCodes) {
        if (locale === 'en') continue
        const owner = enBySlug.get(slugFor(tool, locale))
        if (owner && owner !== tool.id) shadows.push(`${locale}:${tool.id} shadows en of ${owner}`)
      }
    }
    expect(shadows).toEqual([])
  })

  it('generates for exactly the registry tools, no orphans', () => {
    // A tool removed from the registry leaves its slugs behind, and a tool
    // added without running `npm run tools:slugs` has none. Both are quiet.
    const ids = new Set(TOOLS.map((t) => t.id))
    expect(Object.keys(LOCALE_SLUGS).filter((id) => !ids.has(id))).toEqual([])
    expect([...ids].filter((id) => !LOCALE_SLUGS[id])).toEqual([])
  })
})
