// Generated by electe-web/scripts/export-tools-repo.ts from electe-migration@8e52bf6 on 2026-09-29. Do not edit here: change the source and re-export.
import { defaultLocale } from './locales'
import { slugFor, type ToolDef } from './registry'

export const TOOLS_ORIGIN = "https://tools.electe.net"

/** The locale's root on the property host: '' for English, '/it' otherwise. */
export const propertyBase = (locale: string): string => (locale === defaultLocale ? '' : `/${locale}`)

/** The index page in a locale. */
export const indexUrl = (locale: string = defaultLocale): string =>
  `${TOOLS_ORIGIN}${propertyBase(locale) || '/'}`

/** A tool's live page in a locale (its slug there, percent-encoded). */
export const toolUrl = (tool: ToolDef, locale: string = defaultLocale): string =>
  `${TOOLS_ORIGIN}${propertyBase(locale)}/${encodeURIComponent(slugFor(tool, locale))}`
